### ISSUE TITLE
ImageManipulation::castDimension triggers exceptions with values other than string or int

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-assets#103]
Seems like this was introduced with `1.0.1`. Suddenly `ImageManipulation` starts throwing several exceptions for me, because of this change.

There are modules (as well as my own code) that use  `round(…)` to pass image dimensions to image manipulation methods, but the result of that is always a `float` and will throw an exception.
It seems like the `filter_var($value, FILTER_VALIDATE_INT)` doesn't like floats…

Doesn't this violate SemVer as well?

**Comment by bummzack** [comment]
Wouldn't it be good enough to replace this:

    if (!is_int($value) && !(is_string($value) && filter_var($value, FILTER_VALIDATE_INT)))

With this:

    if (!is_numeric($value))

Or am I missing something important?

**Comment by dhensby** [comment]
Hmm, this does look like it needs fixing and is a quite a risky change to be putting into a patch release. I've commented on the original PR and hopefully we'll get a PR in the next few days to resolve this.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/105
