### ISSUE TITLE
MigrateFileTask not working in SilverStripe 4.1 

### ISSUE THREAD

**Issue by schellmax** [silverstripe/silverstripe-assets#123]
MigrateFileTask doesn't seem to be ready for SilverStripe 4.1, tried using it without success.
Found at least one issue: the new 'public' folder (introduced in 4.1).

so the following code in MigrateFileTask doesn't work:
```php
        // Make sure this legacy file actually exists
        $path = $base . '/' . $legacyFilename;
```

it should be 
```php
        // Make sure this legacy file actually exists
        $path = $base . '/public/' . $legacyFilename;
```

this is a little tricky though, as using the 'public' folder isn't strictly required.

This change made the MigrateFileTask succeed for all Files for me, but afterwards all Images in my '/public/assets/Uploads' folder had 0 bytes length - might not be related though, will try it with a SilverStripe 4.0 install.

**Comment by dhensby** [comment]
@tractorcow

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-assets/pull/127
