### ISSUE TITLE
Framework 4.0 incompatibility

### ISSUE THREAD

**Issue by filiplikavcan** [silverstripe/silverstripe-assets#125]
This https://github.com/silverstripe/silverstripe-assets/commit/4f946aaf9eadf9361ed401a5151d1852778e002c#diff-2555baeffdbc2d317fe2e2d5c6e2f396R9 is not compatible with framework 4.0 https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Security/InheritedPermissions.php#L92

**Comment by dhensby** [comment]
It looks like our `composer.json` should be listing `"framework": "^4.1"` as a constraint as it's not BC with 4.0.

@filiplikavcan how are you using assets ^1.1 with SS ^4.0, that's not a typical install?

**Comment by filiplikavcan** [comment]
I manually upgraded silverstripe/assets because I thought this issue is not pushed into 1.0: https://github.com/silverstripe/silverstripe-assets/pull/111 Now I see it is so I can downgrade.

It'll be fine to update composer dependency version anyway.

**Comment by dhensby** [comment]
@filiplikavcan ah, ok, so with my proposed fix you'd have got a dependency resolution error from composer prompting you to upgrade framework to 4.1(which is what you want).

**Comment by filiplikavcan** [comment]
Yup. I'll downgrade assets for now because I cannot upgrade framework, but yes. ;)

**Comment by tractorcow** [comment]
Sorry we don't regularly bump individual module dependencies; Normally we rely on recipes to tie together module dependencies. You can try `composer recipe-require silverstripe/recipe-core 1.something.somethingelse` to get a list of co-compatible modules.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/126

**Comment by dhensby** [comment]
this may be an argument for having a `--prefer-lowest` build in our test suites or bumping out deps when we branch... but  I'd like to avoid arbitrarily bumping a dependency we don't need to.

**Comment by tractorcow** [comment]
That wouldn't work in this case, because --prefer-lowest would still pull in the lowest dependency from the recipe's point of view (which would require 4.1), but in this case the recipe isn't used directly.

**Comment by dhensby** [comment]
@tractorcow it would only do that now we made that change, my point is that it would have flagged a failure against 4.0 and we'd have made this change before tagging stable

**Comment by tractorcow** [comment]
No, it would ignore this change, and fix to the changes in the recipe.

See https://github.com/silverstripe/recipe-core/blob/1.1/composer.json

Installed by https://github.com/silverstripe/silverstripe-assets/blob/1.1/.travis.yml#L30

The framework 4.1.x-dev would (and has until now) been forcing framework 4.1 for tests.

We'd never have installed 4.0 for testing.
