### ISSUE TITLE
Image extension and renderWith renders original image

### ISSUE THREAD

**Issue by andreaslindahl** [silverstripe/silverstripe-assets#128]
I don't know if this is a bug, or if I'm just being stupid, but here goes...

I'm trying to extend SilverStripe\Assets\Image to add a custom method similar to Tag(), but which returns an image tag with some other attributes as well. Works great as long as I wish to show the original image. However, if I do for example `$Image.FillMax(400,400).TagLazyLoading` it always returns an image tag with the original image and not the resized one. My SS template is used, but the URL of the image refers to the original image.

Here's the method in my extension class:

```
public function getTagLazy() {
    $url = $this->owner->getURL();
        if (empty($url)) {
            return "";
        }
        return $this->owner->renderWith("Includes/LazyImageTag");
}
```

And I register my extension in my YAML config like this:

```
SilverStripe\Assets\Image:
  extensions:
    - ImageExtension
```
And in my LazyImageTag.ss I just have this:

`<img data-src="$URL.ATT" alt="$Title.ATT" />`

**Comment by andreaslindahl** [comment]
I just discovered that it works if I extend DBFile instead of Image. But is this expected behavior?

**Comment by tractorcow** [comment]
@andreaslindahl sorry it's not apparent, but actually you need to extend both classes.

**Comment by tractorcow** [comment]
In the future we should shift the ImageManipulation trait into a proper service, so that there is a single injectable extension point.

**Comment by tractorcow** [comment]
I've raised an enhancement at https://github.com/silverstripe/silverstripe-assets/issues/130
