### ISSUE TITLE
TinyMCE Embedded image - "edit image" fails to load form data

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#131]
When trying to edit the detail of an image in the WYSIWYG, the _Placement_ tab in the modal doesn't remember the previous data in the form, until:
* the form is clicked
* keypress is performed

This can cause an editor to unwittingly lose their placement information on their image.

# Steps to reproduce
1. Edit a page
1. Insert an image in the WYSIWIG while providing placement information (e.g.: dimensions size, alt, aligngment). Your image will be added to the WYSIWYG.
1. Click on the image in the WYSIWYG and click on the _Insert from File_ button in the toolbar.
1. The _File Insert_ modal window will be loaded with your image pre-selected, however your placement information that was provided in step 2 is not pre-populated in the form.
1. Click the _Insert File_ button. The Modal will be close and the image in the WYSIWYG looses all its custom placement info.

[![Youtube video of bug](http://img.youtube.com/vi/VPEHhj4cm-0/0.jpg)](https://www.youtube.com/watch?v=VPEHhj4cm-0&feature=youtu.be)

# Expected behavior
The _Placement_ tab in the _Insert Media_ modal should be pre-populated with existing placement information when editing an existing image from a WYSIWYG.

# Related issue
* #129 
* https://github.com/silverstripe/silverstripe-cms/issues/706

# PR
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/801 (did not fix)
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1213

**Comment by lukereative** [comment]
This issue is also relevant https://github.com/silverstripe/silverstripe-cms/issues/706 as this dropdown should probably use the same placement UI as the 'Insert Media' dialog (which is custom radios)
<img width="621" alt="screen shot 2018-07-02 at 11 45 14 am" src="https://user-images.githubusercontent.com/1415622/42140072-7d86dcc4-7ded-11e8-9db3-f28d88bed33c.png">

**Comment by TomOudeRengerink** [comment]
@maxime-rainville Looks like this issue stil exists? Image attributes are saved correctly inside the HTML but when retrieving the data in the CMS pop-up its not loaded properly. Any updates on this?

**Comment by maxime-rainville** [comment]
@TomOudeRengerink Can you let us know what version you are using?

**Comment by maxime-rainville** [comment]
Just replicated locally. It's the entire insert image form that doesn't load ... not just the placement info.

**Comment by maxime-rainville** [comment]
@brynwhyman Just tested this all the way back to cms 4.6. So it seems to have been broken for a while.

https://youtu.be/YGRNIpab3vc

**Comment by brynwhyman** [comment]
Feels like at least impact/high to me. There's no workaround to getting this information back.

**Comment by brynwhyman** [comment]
There's a duplicate report that I'll close here: https://github.com/silverstripe/silverstripe-asset-admin/issues/1137

**Comment by GuySartorelli** [comment]
silverstripe/silverstripe-asset-admin#1137 had its name amended to reflect that the entire form fails to load the correct data. Can we amend the title of this one similarly?

**Comment by brynwhyman** [comment]
Yes, thanks @GuySartorelli good catch. Updated the title and description to include the following:

> When trying to edit the detail of an image in the WYSIWYG, the _Placement_ tab in the modal doesn't remember the previous data in the form, until:
> * the form is clicked
> * keypress is performed

**Comment by brynwhyman** [comment]
This has been fixed in 1.7.x and 1.8.x of silverstripe/asset-admin. See: https://github.com/silverstripe/silverstripe-asset-admin/pull/1213

Just discussing doing patch releases of each branch now.

**Comment by brynwhyman** [comment]
![form-not-lost](https://user-images.githubusercontent.com/15868440/123195379-2d318800-d4fc-11eb-9848-50f0abe5b29f.gif)


([excuse the floating alignment/ edit button](https://github.com/silverstripe/silverstripe-admin/issues/1230))

**Comment by brynwhyman** [comment]
Releases made: https://github.com/silverstripe/silverstripe-asset-admin/releases

**Comment by TomOudeRengerink** [comment]
@brynwhyman Great! Thanks for the update!
