### ISSUE TITLE
FileMigrationHelper using BASE_PATH

### ISSUE THREAD

**Issue by extravio** [silverstripe/silverstripe-assets#132]
Shouldn't the base path default to Director::publicFolder() instead of BASE_PATH in FileMigrationHelper::run (line 45) ?
As part of a migration from 3.x to SS4.1, I moved the assets folder to public/ and the MigrateFileTask doesn't work with BASE_PATH.
ref: https://docs.silverstripe.org/en/4/changelogs/4.1.0/

**Comment by tractorcow** [comment]
This is fixed with https://github.com/silverstripe/silverstripe-assets/pull/127
