### ISSUE TITLE
Images orientated by EXIF data render incorrectly in templates

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-assets#133]
Standalone issue created from https://github.com/silverstripe/silverstripe-assets/pull/100#issuecomment-366676938

With `force_resample` off, any image uploaded that has had its orientation changed will render in its pre-rotated state by default in a template.

For example, with a photo taken on a phone, I had to do the following to get my portrait image to render the right way up:

```diff
- <img src="$Link">
+ <img src="$Resampled.URL">
```

And the same with an `<a>` tag I wrapped another `<img>` in.

**Comment by GuySartorelli** [comment]
Added to CMS 5 epic because the proposed solution (see link in description) involves modifying an interface API which is a breaking change.

**Comment by GuySartorelli** [comment]
This missed CMS 5 - and in CMS 6 intervention/image will auto-rotate based on EXIF data automatically. Closing because that will resolve it, and it seems it can't be sensibly resolved outside of a major release.
