### ISSUE TITLE
PublicAssetAdapter has problematic parentUrlPrefix value

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-assets#14]
As discussed with @sminnee and @tractorcow on Slack.

I noticed today that asset URLs were broken on my local install (both relative and absolute) in SS4 `dev-master`, for example:

```html
<a href="/\assets/Gallery/file.jpg"><img src="http://host.dev//\assets/Gallery/file.jpg"></a>
```

It seems to be an issue with [SilverStripe\Assets\Flysystem\PublicAssetAdapter](https://github.com/silverstripe/silverstripe-assets/blob/master/src/Flysystem/PublicAssetAdapter.php#L43), specifically line 43:

```php
$this->parentUrlPrefix = substr($path, strlen(BASE_PATH));
```

The `BASE_PATH` constant on my install does not have a trailing slash, so the above code will generate a problematic prefix with a leading slash.  To illustrate:

```
Value of BASE_PATH: "W:\Repos\Apps\reponame"
Value of $path: "W:\Repos\Apps\reponame\assets"
Value of $this->parentUrlPrefix: "\assets"
```

I've temporarily worked around this by wrapping a `trim` around the prefix in the `getPublicUrl` method:

```php
public function getPublicUrl($path)
{
    return Controller::join_links(Director::baseURL(), trim($this->parentUrlPrefix, '/\\'), $path);
}
```

## Environment

- SilverStripe 4 `dev-master`
- PHP 5.6.29
- Apache 2.4.23 (x64)
- Firefox Developer Edition 54.0a2 (2017-04-18) (x64)
- Windows 10 Pro x64 1607 Build 14393.1066

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/17
