### ISSUE TITLE
"Replace" button can't function when not accessed from main Assets tab

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-assets#146]
**To reproduce:**
1. Open the assets interface from an UploadField or WYSIWYG editor (not via the main Assets tab).
2. Select an image, so it's details display on the right-hand side.
3.  Click on the "Replace" upload button that appears on the right of the preview: ![image](https://user-images.githubusercontent.com/329880/41482469-a48892c2-70cd-11e8-8a92-836e44f007b9.png)
4. Select an alternative image to replace it with from your computer.

**What happens:**
A message appears saying _"Upload successful, the file will be replaced when you Save."_

But there is no "Save" button! Only an "Insert File" button and clicking it does not trigger the image to be replaced with the new image.

![](http://spdr.me/gLF9zB+)

**What should happen:**
Either:
A. The ![image](https://user-images.githubusercontent.com/329880/41482469-a48892c2-70cd-11e8-8a92-836e44f007b9.png) button shouldn't appear in the first place, within this mode.
B. Upon using the replace button, the "Insert file" button should be replaced with Save and Publish buttons.
C. Clicking "Insert file" should save the image, replace the file and insert the new one.

**Comment by lukereative** [comment]
This had an existing issue – https://github.com/silverstripe/silverstripe-asset-admin/issues/756) and a PR to disable it which has now been merged – https://github.com/silverstripe/silverstripe-asset-admin/pull/814

**Comment by lukereative** [comment]
This had an existing issue – https://github.com/silverstripe/silverstripe-asset-admin/issues/756) and a PR to disable it which has now been merged – https://github.com/silverstripe/silverstripe-asset-admin/pull/814
