### ISSUE TITLE
File/Image should cast use of "getTag" to HTMLFragment.

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-assets#147]
**The problem**
Calling `$MyImage.Tag`  will just render out an `<img src>` tag as plain text.

**The solution**
Extend File's casting config to `Tag` and `getTag`. This allows you to use $Tag and $getTag in templates.
```
private static $casting = array (
        'TreeTitle' => 'HTMLFragment',
        'Tag' => 'HTMLFragment',
        'getTag' => 'HTMLFragment',
);
```

Source:
https://github.com/silverstripe/silverstripe-assets/blob/master/src/File.php#L160

**Current workaround / alternate solution**
I was using $Tag in a `<% with $Thumbnail %>` block. Instead I'm now using $Me

**Comment by maxime-rainville** [comment]
All done.
