### ISSUE TITLE
File::getCMSFields() code has decayed

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-assets#15]
Since asset-admin module moved to using form factories to generate edit forms, the code in getCMSFields() has decayed due to disuse.

This code should be cleaned up in anticipation of being useful in a file edit dialog outside of asset admin, such as a gridfield, and asset-admin dependencies (e.g. translation strings, css classes) removed.

# PR

 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/60

**Comment by chillu** [comment]
Good point, please strip it back to the basics. Also mention in the PHPDoc that this isn't actually used for AssetAdmin

**Comment by tractorcow** [comment]
Fixed with #60
