### ISSUE TITLE
Combined files broken with the fixes for SS-2018-014

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-assets#151]
When using combined files by default they are placed in ``assets/_combinedfiles`` in both SilverStripe 4.1 (and prior) with the changes to resolve SS-2018-014 these are now blocked and return a 403 response. As well it's also worth noting that there is a ``_tinymce`` folder in assets I'm not sure if this is used or not but it would also be blocked because of those changes.

As mentioned this also affects 3.5, 3.6, and 3.7 since similar changes were made to the default htaccess for those versions as well.

One workaround I was able to get working after some fussing was using the information [here](https://docs.silverstripe.org/en/4/developer_guides/templates/requirements/#configuring-combined-file-storage) to re-map the combined files folder out into the public folder, but the example didn't work out of the box.

**Comment by UndefinedOffset** [comment]
Something like the below would work in the 1.1 branch, but it may not be the right approach ;) and it doesn't solve the issue on IIS servers. It also runs into the same issue as #141, since it's using the same file name matching method.

```diff
diff --git a/src/Flysystem/AssetAdapter.php b/src/Flysystem/AssetAdapter.php
index bfbf176..8cd3b24 100644
--- a/src/Flysystem/AssetAdapter.php
+++ b/src/Flysystem/AssetAdapter.php
@@ -11,6 +11,7 @@ use SilverStripe\Core\Config\Config;
 use SilverStripe\Core\Config\Configurable;
 use SilverStripe\ORM\ArrayList;
 use SilverStripe\View\ArrayData;
+use SilverStripe\View\Requirements;
 use SilverStripe\View\SSViewer;
 
 /**
@@ -188,7 +189,10 @@ class AssetAdapter extends Local
 
         $viewer = SSViewer::create(array($template));
         $result = (string)$viewer->process(new ArrayData(array(
-            'AllowedExtensions' => $allowedExtensions
+            'AllowedExtensions' => $allowedExtensions,
+            'AssetsFolder' => preg_quote(ASSETS_DIR),
+            'CombinedFilesEnabled' => Requirements::get_combined_files_enabled(),
+            'CombinedFilesFolder' => preg_quote(Requirements::backend()->getCombinedFilesFolder())
         )));
 
         Config::unnest();
diff --git a/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss b/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss
index 87104b0..db17751 100644
--- a/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss
+++ b/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss
@@ -24,6 +24,12 @@ AddHandler default-handler php phtml php3 php4 php5 inc
     RewriteCond %{REQUEST_FILENAME} -f
     RewriteRule error[^\\\\/]*\\.html$ - [L]
 
+    <% if $CombinedFilesEnabled %>
+        # Allow combined files
+        RewriteCond %{REQUEST_URI} ^{$baseURL}{$AssetsFolder}/{$CombinedFilesFolder}\/[^.]*\\.(?i:css|js)$
+        RewriteRule .* - [L]
+    <% end_if %>
+
     # Block invalid file extensions
     RewriteCond %{REQUEST_URI} !^[^.]*\\.(?i:css|js<% loop $AllowedExtensions %>|$Extension<% end_loop %>)$
     RewriteRule .* - [F]

```

**Comment by tractorcow** [comment]
@UndefinedOffset can you tell us your apache version? I have a feeling there are a few related issues where different environments would experience different behaviour. I wonder if it's apache 2.2 / 2.4 incompatibility?

**Comment by tractorcow** [comment]
I've posted a potential fix to https://github.com/silverstripe/silverstripe-assets/issues/141#issuecomment-400854468, but I'm not sure if that will fix this issue also.

**Comment by UndefinedOffset** [comment]
Pretty sure both environments I experienced it on are Apache 2.4, the love is for sure and I'm fairly confident my dev is as well.

**Comment by UndefinedOffset** [comment]
Your fix in that issue should fix part of the problem but the issue is mainly that js and CSS files are explicitly blacklisted in the assets folder but combined files lives on there by default. That fix should be able to fix the regex issue in my diff but it would still block CSS and js in assets. Which is definitely important to do but it breaks combined files :S

**Comment by tractorcow** [comment]
Does it allow css in the root, or folders with normal file structures? E.g. assets/Uploads/somefile.css?

**Comment by tractorcow** [comment]
The fix isn't to blacklist those extensions, it hard-codes both css|js in the whitelist.

**Comment by UndefinedOffset** [comment]
ah ok i was reading it backwards ;) oops 141 is definitely the issue since the combined files being blocked have two dots. Thanks
