### ISSUE TITLE
Misleading annotation: the parameters order is wrong

### ISSUE THREAD

**Issue by leochenftw** [silverstripe/silverstripe-assets#155]
https://github.com/silverstripe/silverstripe-assets/blob/62720a6eedde7af9a5af0b8bb946946e7baa008e/src/Image_Backend.php#L169

refer to 
![image](https://user-images.githubusercontent.com/8662044/43839004-1c49789e-9b71-11e8-98fc-1cff20b39a22.png)

The correct order should be $width, $height, $left, $top - this works for both GD & Imagick backend.

**Comment by robbieaverill** [comment]
Would you be interested in making a PR to fix this?

**Comment by zzdjk6** [comment]
https://github.com/silverstripe/silverstripe-assets/blob/8f36b033b8cae5245a0b3dca74ac3a7ccdb761cb/src/InterventionBackend.php#L660-L675

The order of arguments seems correct, since they are re-ordered before calling `Intervention\..\CropCommand`.

**Comment by kinglozzer** [comment]
Thanks @zzdjk6
