### ISSUE TITLE
Add file folder DatabaseException with PostgreSQL

### ISSUE THREAD

**Issue by jacobaarnold** [silverstripe/silverstripe-assets#176]
## Affected Version

```
phpunit/phpunit            5.7.27
silverstripe-themes/simple 3.2.0 
silverstripe/postgresql    2.0.2 
silverstripe/recipe-cms    4.2.1 
silverstripe/recipe-plugin 1.3.0 
```

## Description

When running a clean base install of Silverstripe 4.2.1 against PostgreSQL 10.0 using using pg_connect, clicking the "Add Folder" button under Files in the CMS admin results in an error:

```
error-log.ERROR: Uncaught Exception SilverStripe\ORM\Connect\DatabaseException: "Couldn't run query:  SELECT DISTINCT "Group"."ClassName", "Group"."LastEdited", "Group"."Created", "Group"."Title", "Group"."Description", "Group"."Code", "Group"."Locked", "Group"."Sort", "Group"."HtmlEditorConfig", "Group"."ParentID", "Group"."ID",  			CASE WHEN "Group"."ClassName" IS NOT NULL THEN "Group"."ClassName" 			ELSE  E'SilverStripe\\Security\\Group' END AS "RecordClassName"  FROM "Group"  WHERE ("Group"."ID" = $1)  LIMIT 1  ERROR:  invalid input syntax for integer: "unchanged"" at /var/www/html/html/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php line 64 {"exception":"[object] (SilverStripe\\ORM\\Connect\\DatabaseException(code: 0): Couldn't run query:\n\nSELECT DISTINCT \"Group\".\"ClassName\", \"Group\".\"LastEdited\", \"Group\".\"Created\", \"Group\".\"Title\", \"Group\".\"Description\", \"Group\".\"Code\", \"Group\".\"Locked\", \"Group\".\"Sort\", \"Group\".\"HtmlEditorConfig\", \"Group\".\"ParentID\", \"Group\".\"ID\", \n\t\t\tCASE WHEN \"Group\".\"ClassName\" IS NOT NULL THEN \"Group\".\"ClassName\"\n\t\t\tELSE  E'SilverStripe\\\\Security\\\\Group' END AS \"RecordClassName\"\n\nFROM \"Group\"\n\nWHERE (\"Group\".\"ID\" = $1)\n\nLIMIT 1\n\nERROR:  invalid input syntax for integer: \"unchanged\" at /var/www/html/html/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php:64)"} []
```

Running the same base install against MySQL, folders can be added successfully.

## Steps to Reproduce

In SS 4.2.1 with PostgreSQL module, navigate to the CMS admin, click Files, then "Add Folder." "Internal Server Error" appears in red at the top of the right pane.

## PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8592
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8672
- [x] https://github.com/silverstripe/silverstripe-admin/pull/782
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/894

**Comment by maxime-rainville** [comment]
Is there anything left to do on this now that https://github.com/silverstripe/silverstripe-framework/pull/8592 has been merged?

**Comment by dnsl48** [comment]
Yes, as per our discussion in [#8592](https://github.com/silverstripe/silverstripe-framework/pull/8592), there's another PR with breaking changes to be done for the next major release.

**Comment by maxime-rainville** [comment]
@dnsl48 I re ran the builds. Looks like `admin` fails on our old nemesis, the "Are you sure you want to navigate away from this page" alert. Not sure what is failing the `asset-admin` PR.

**Comment by ScopeyNZ** [comment]
And to leave you more confused: https://travis-ci.org/open-sausages/silverstripe-asset-admin/builds/467298904

**Comment by dnsl48** [comment]
@maxime-rainville haha, that's the same exact spot I was fixing a week ago. Shouldn't take me too long to figure out what's going on in there. Last time it was entwine racing with changetracker. This time I already know what we're dealing with... (hopefully)

**Comment by maxime-rainville** [comment]
Everything has been merged. Let's us move on.

**Comment by power-media** [comment]
Hello. I am still observing problem when trying to create folder in "Files" section, while running SS version 4.3.1 and Postgres 10.6. Error log contains "...ERROR:  invalid input syntax for integer: \"unchanged\" at ...". As I see this issue has been resolved and merged... what I'm doing wrong?

**Comment by dnsl48** [comment]
Hey @power-media 
could you give us the `composer show` of your project?

**Comment by power-media** [comment]
Here you go:

`composer/ca-bundle                        1.1.4   Lets you find a path to the system CA bundle, and includes a fallb...
composer/installers                       v1.6.0  A multi-framework Composer library installer
doctrine/instantiator                     1.1.0   A small, lightweight utility to instantiate objects in PHP without...
embed/embed                               v3.3.8  PHP library to retrieve page info using oembed, opengraph, etc
guzzlehttp/guzzle                         6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                       v1.3.1  Guzzle promises library
guzzlehttp/psr7                           1.5.2   PSR-7 message implementation that also provides common utility met...
intervention/image                        2.4.2   Image handling and manipulation library with support for Laravel i...
league/csv                                8.2.3   Csv data manipulation made easy in PHP
league/flysystem                          1.0.50  Filesystem abstraction: Many filesystems, one API.
league/flysystem-azure-blob-storage       0.1.5
m1/env                                    2.1.2   Env is a lightweight library bringing .env file parser compatibili...
marcj/topsort                             1.1.0   High-Performance TopSort/Dependency resolving algorithm
microsoft/azure-storage-blob              1.2.0   This project provides a set of PHP client libraries that make it e...
microsoft/azure-storage-common            1.2.0   This project provides a set of common code shared by Azure Storage...
monolog/monolog                           1.24.0  Sends your logs to files, sockets, inboxes, databases and various ...
myclabs/deep-copy                         1.8.1   Create deep copies (clones) of your objects
nikic/php-parser                          v4.2.1  A PHP parser written in PHP
paragonie/random_compat                   v2.0.18 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common           1.0.1   Common reflection classes used by phpdocumentor to reflect the cod...
phpdocumentor/reflection-docblock         4.3.0   With this component, a library can provide support for annotations...
phpdocumentor/type-resolver               0.4.0
phpspec/prophecy                          1.8.0   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                 4.0.8   Library that provides collection, processing, and rendering functi...
phpunit/php-file-iterator                 1.4.5   FilterIterator implementation that filters files based on a list o...
phpunit/php-text-template                 1.2.1   Simple template engine.
phpunit/php-timer                         1.0.9   Utility class for timing
phpunit/php-token-stream                  2.0.2   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                           5.7.27  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects              3.4.4   Mock Object library for PHPUnit
psr/cache                                 1.0.1   Common interface for caching libraries
psr/container                             1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/http-message                          1.0.1   Common interface for HTTP messages
psr/log                                   1.1.0   Common interface for logging libraries
psr/simple-cache                          1.0.1   Common interfaces for simple caching
ralouphie/getallheaders                   2.0.5   A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup        1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator                      1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                            1.4.3   Diff implementation
sebastian/environment                     2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                        2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                    1.1.1   Snapshotting of global state
sebastian/object-enumerator               2.0.1   Traverses array structures and object graphs to enumerate all refe...
sebastian/recursion-context               2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations             1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                         2.0.1   Library that helps with managing the version number of Git-hosted ...
sendgrid/php-http-client                  3.9.6   HTTP REST client, simplified for PHP
sendgrid/sendgrid                         7.2.1   This library allows you to quickly and easily send emails through ...
silverstripe-themes/simple                3.2.0   The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/admin                        1.3.1   SilverStripe admin interface
silverstripe/asset-admin                  1.3.1   Asset management for the SilverStripe CMS
silverstripe/assets                       1.3.1   SilverStripe Assets component
silverstripe/campaign-admin               1.3.1   SilverStripe campaign admin interface
silverstripe/cms                          4.3.1   The SilverStripe Content Management System
silverstripe/config                       1.0.12  SilverStripe configuration based on YAML and class statics
silverstripe/display-logic                2.0.2   Allows assignment of conditions for display and hide of specific f...
silverstripe/errorpage                    1.3.1   ErrorPage component for SilverStripe CMS
silverstripe/framework                    4.3.1   The SilverStripe framework
silverstripe/graphql                      3.0.1   GraphQL server for SilverStripe models and other data
silverstripe/lumberjack                   2.0.1   A module to make managing pages in a GridField easy without losing...
silverstripe/postgresql                   2.1.0   SilverStripe now has tentative support for PostgreSQL ('Postgres')
silverstripe/recipe-cms                   4.3.1   SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-core                  4.3.1   SilverStripe framework-only core recipe
silverstripe/recipe-plugin                1.3.0   Helper plugin to install SilverStripe recipes
silverstripe/reports                      4.3.1   Reports module for SilverStripe CMS
silverstripe/siteconfig                   4.3.1   Site wide settings administration.
silverstripe/vendor-plugin                1.4.0   Allows vendor modules to expose directories to the webroot
silverstripe/versioned                    1.3.1   SilverStripe Versioned component
silverstripe/versioned-admin              1.1.1   SilverStripe versioned admin interface
swiftmailer/swiftmailer                   v5.4.12 Swiftmailer, free feature-rich PHP mailer
symbiote/silverstripe-gridfieldextensions 3.2.1   A collection of useful grid field components
symfony/cache                             v3.4.22 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                            v3.4.22 Symfony Config Component
symfony/filesystem                        v4.2.3  Symfony Filesystem Component
symfony/finder                            v3.4.22 Symfony Finder Component
symfony/polyfill-apcu                     v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype                    v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring                 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/translation                       v2.8.49 Symfony Translation Component
symfony/yaml                              v3.4.22 Symfony Yaml Component
webmozart/assert                          1.4.0   Assertions to validate method input/output with nice error messages.
webonyx/graphql-php                       v0.8.0  A PHP port of GraphQL reference implementation`

**Comment by ScopeyNZ** [comment]
I'm pretty sure the fix is _not_ bundled in 4.3.1. We'll have to do a follow-up 4.3.2 release.

You can confirm this with GitHub UI by looking at the commit: https://github.com/silverstripe/silverstripe-framework/pull/8592/commits/4b4fbabed5d70bf577e4b0d6fdbc9dab9da80451

The tags the commit exists in are listed - and there's no versions of 4.3.x within that list.

**Comment by dnsl48** [comment]
@power-media  yes, @ScopeyNZ is correct
`4.3.1` [only contains a security fix](https://docs.silverstripe.org/en/4/changelogs/4.3.1/).
That's been done so people would be able to update without accidentally receiving regression bugs.

This particular fix is scheduled to hit `4.3.2` release, which is going to follow shortly.

**Comment by power-media** [comment]
Thanks for clarification @ScopeyNZ and @dnsl48, I am looking forward to be able to upgrade to 4.3.2 version so, as my project needs it urgently (and problem has just been discovered).
Any rough estimate when this could happen?

**Comment by ScopeyNZ** [comment]
We expect it'll be released at least by the 7th of March.

**Comment by maxime-rainville** [comment]
The 4.3.2 release is scheduled for sometime in March. If you want the fix right away in your dev environment, you can try adding this line in your `composer.json` file:
```
    "silverstripe/framework": "4.3.x-dev as 4.3.1"
```

Beware, that you will get some pre-release dependencies if you do that, so that's probably not suitable for production.

**Comment by power-media** [comment]
Hello @ScopeyNZ @maxime-rainville , would you have any news about release date, with change that we spoke about?

**Comment by kinglozzer** [comment]
@power-media 4.3.2 has been release, it looks like all the commits above were included. Have you had a chance to upgrade and try it?

**Comment by maxime-rainville** [comment]
We didn't do a patch release for 4.2, 4.1 and 4.0.

**Comment by power-media** [comment]
Thanks @kinglozzer, I tried it and it worked!
