### ISSUE TITLE
Images sometimes not loading (404 not found)

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-assets#179]
## Affected Version

4.0.3

## Description

Published images return 404 when user agent changes (ie. session is destroyed). This happens for logged in users and non-logged in users.

## Steps to Reproduce

* Using chrome
* Publish an image which appears on a page
* Access the page (with or without being logged in)
* You can see the image in the browser
* Open chrome dev tools, using the responsive mode and select a mobile device (ie, iphone)
* Refresh the page 

Expected: 
* The image appears

Actual: 
* The image does not appear. 
* If the user was logged in when the page was loaded, they'll be logged out.

## Why

When using the responsive dev tool in chrome it mimics other devices user agents. In `Session::init()`  a check is made to match the session user agent against the request user agent. If the agent doesn't match it will destroy the session. This causes a logged in user to be logged out.

Even if a session was destroyed, I'd expect that published images were still viewable.

**Comment by maxime-rainville** [comment]
Was the page published as well? We've made some changes on how related versioned object get published in later minor release, so this issue might have been resolved already.

**Comment by micmania1** [comment]
@maxime-rainville yeah, the problem is purely because the user agent changes and invalidates the session. Not sure that can be solved without impacting security.

**Comment by mr45144** [comment]
This seems to make testing unnecessarily hard - if it was such an important security issue would it not have been implemented this way many versions ago. Would it be possible to make user-agent only part of determininhg the end of a session - eg if the user agent changes but the ipaddress doesn't and the time is (pick a suitable value) then I don't see how that would be an attack vector. If I were determined on an attack from that machine then changing the user-agent would be pointless

**Comment by mr45144** [comment]
I don't have a tool available to me at the moment - has anyone tried this with automation that runs tests across a suite of browsers?

**Comment by kinglozzer** [comment]
@mr45144 A new config flag to disable user-agent validation will be available in 4.5 (https://github.com/silverstripe/silverstripe-framework/pull/9170) when it’s released. In fact, I think that PR being merged means this issue can be closed, as the crux of this issue was the session being destroyed when the UA changes
