### ISSUE TITLE
3.x: 403 errors for moved asset files

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-assets#180]
I am trying to implement 301 redirects for files stored in assets. I got into this issue when we rebuilt a site and discovered that we get a lot of 403 'not allowed' errors for files in the assets directory that have moved.
When a folder exists, but a file in that folder doesn't, you get a 404 error (e.g. `www.domain.tld/assets/folder/nofile.pdf`), as expected.
But when you hit an URL to a file in a non-existing folder, you get a 403 (e.g. `www.domain.tld/non-existing/no-file.pdf`).

The 403 errors are caused by ‘Deny from all’ in the assets/.htaccess file. This seems to have priority over any redirects added to the main .htaccess file for files that have changed path. It looks like the ‘Deny from all’ prohibits apache from checking whether the file actually exists.

To fix that, I have removed the global ‘Deny from all’ and changed the regex to the following using a negation:
```
<FilesMatch ".(!(?i:html|htm|xhtml|js|css|bmp|png|gif|jpg|jpeg|ico|pcx|...|jar|xml|pdf|gpx|kml))$">
Deny from all
</FilesMatch>
```
Is that safe to use? Should that be changed in core?

Also, any 404 handlers in SS (e.g. misdirection, etc) don't work for asset files because of 
```
RewriteCond %{REQUEST_FILENAME} !-f
```
in the root .htaccess file. 

If I add
```
RewriteCond %{REQUEST_URI} ^assets/ [NC,OR]
```
right before that line in the main .htaccess file, this works, but of course it also means that every request to a file goes through the whole SS controller stuff, which makes the site slower. With this the 404 handlers also works for asset files.

**Comment by maxime-rainville** [comment]
I don't think this is worth fixing in SS3. And it won't affect SS4.

**Comment by xini** [comment]
I dare to disagree.

**Comment by maxime-rainville** [comment]
Sadly [Silverstripe 3 has entered limited support](https://www.silverstripe.org/software/roadmap/). This means we'll only be release security fixes from now on.

**Comment by xini** [comment]
as usual. just wait long enough.
