### ISSUE TITLE
File uploading doesn't auto-rename files when working with CDNContent / S3 Modules

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-assets#181]
In Silverstripe 3.x, due to files not existing on the local disk, S3 files aren't being checked to see if there are duplicates properly.

See here:
https://github.com/silverstripe/silverstripe-framework/blob/3.6.2/filesystem/Upload.php#L185

My proposed solution to this is either:
- Update this to check for the following (or similar)
`while(file_exists("$base/$relativeFilePath") || File::get()->filter('Filename', $relativeFilePath))->count() > 0`
- Add an extension call here so custom logic can check for the existence of the file.

**Comment by maxime-rainville** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
