### ISSUE TITLE
Upload validation does not account for file upload fails due to hidden form input "MAX_FILE_SIZE" in filesystem/Upload.php

### ISSUE THREAD

**Issue by cwchong** [silverstripe/silverstripe-assets#187]
When adding a FileField, a hidden input field "MAX_FILE_SIZE" is added. In supported browsers, the file size is checked client-side first based on this value.
If this value is exceeded, the file is not sent to the server, this will cause validation to fail, but incorrectly so due to no file being uploaded instead of file size being exceeded.

In the Upload.validate() function, it should instead check "$this->tmpFile['error'] == 2" prior to file existence checking. The error code 2 implies file size exceeded due to the "MAX_FILE_SIZE" field in the html form.
e.g.

```
public function validate() {
        // we don't validate for empty upload fields yet
        if(!isset($this->tmpFile['name']) || empty($this->tmpFile['name'])) return true;
        // BEGIN EDIT 
        // ^^ tmpFile['name'] still gets passed, but tmpFile['tmp_name'] will not exist
        // if file exceeds the MAX_FILE_SIZE set in the form
        if(isset($this->tmpFile['error']) && ($this->tmpFile['error'] == 2)) {
            $pathInfo = pathinfo($this->tmpFile['name']);
            $ext = (isset($pathInfo['extension'])) ? $pathInfo['extension'] : '';
            $arg = File::format_size($this->getAllowedMaxFileSize($ext));
            $this->errors[] = _t(
                'File.TOOLARGE', 
                'Filesize is too large, maximum {size} allowed',
                'Argument 1: Filesize (e.g. 1MB)',
                array('size' => $arg)
            );
            return false;
        }
        // END EDIT 

        $isRunningTests = (class_exists('SapphireTest', false) && SapphireTest::is_running_test());
        if(isset($this->tmpFile['tmp_name']) && !is_uploaded_file($this->tmpFile['tmp_name']) && !$isRunningTests) {
            $this->errors[] = _t('File.NOVALIDUPLOAD', 'File is not a valid upload');
            return false;
        }
...
}
```

**Comment by maxime-rainville** [comment]
Hi @cwchong. Thanks for getting in touch and sorry it took us so long to get back to you.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
