### ISSUE TITLE
FileMigrationHelper does not work with "legacy_filenames: true"

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-assets#188]
https://github.com/silverstripe/silverstripe-assets/blob/6b599be5568e9d6beefa901a53d58a288ac866ee/src/FileMigrationHelper.php#L125

When running the `MigrateFileTask` after upgrading from SS3.x to SS4.x, If you have `legacy_filenames: true` set in your codebase, it will cause the migration to read and write the same file which causes 0 bytes to be written to each file.

This is because the `$path` and `$filename` variables being parsed refer to the same file (`$path` - absolute path of file, `$filename` - relative path of file) meaning that Flysystem will open up a read handler on $path and then stream its content to $filename which is the same file.

# Related PRs
* #209

**Comment by brettt89** [comment]
Managed to resolve this issue locally by changing the Conflict resolution in the Helper to "Keep original" rather than "Overwrite" when `legacy_filenames` is set to `true`.

https://github.com/silverstripe/silverstripe-assets/blob/6b599be5568e9d6beefa901a53d58a288ac866ee/src/FileMigrationHelper.php#L130

**Comment by purplespider** [comment]
Thanks, I hit this issue too.

Changing:
https://github.com/silverstripe/silverstripe-assets/blob/6b599be5568e9d6beefa901a53d58a288ac866ee/src/FileMigrationHelper.php#L130
To:
`array('conflict' => AssetStore::CONFLICT_USE_EXISTING)`
Seems to fix it, but unsure if this would cause any other side effects.

**Comment by maxime-rainville** [comment]
We've got a PR for 4.4 at #209
