### ISSUE TITLE
Transparency option has been removed from ImageManipulation::Pad()

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-assets#20]
Maybe this was intentional, but 3.x has an argument for transparency: https://github.com/silverstripe/silverstripe-framework/blob/3/model/Image.php#L345.

Will also need to be copied to the backends:

- https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/GD.php#L455
- https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/ImagickBackend.php#L207

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/pull/6777

**Comment by robbieaverill** [comment]
The fix for this is at #23
