### ISSUE TITLE
MigrateFileTask does not check if SubsiteID actually points to a subsite.

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-assets#200]
When migrating Files and Folders using the MigrateFileTask for SS4 upgrades. The migration task does not confirm if the SubsiteID actually refers to a real Subsite. This is causing folders and files to not show up in the CMS after running this task.

E.g. Folder has SubsiteID = 2;
Website only has 1x subsite which has an ID of 3;
**Result:** Folder is not view-able in CMS as its not global and doesn't have a corresponding Subsite to manage with.

Need a hook into MigrateFileTask to set SubsiteID to 0 (global) if Subsite does not exist.

OR - Change functionality so that CMS treats all files with a SubsiteID that doesn't exist as Global.

**Comment by chillu** [comment]
Moved into assets repo, added to "smoother upgrade experience" epic, and added it to our backlog to be planned

**Comment by chillu** [comment]
Lowering priority, if you have a database state where file records point to non-existent subsites, you already have a problem in your 3.x site. You could even argue that it's not really in scope for the file migration task to fix that inconsistency, although it'd be a natural place to perform this additional sanity check.

**Comment by chillu** [comment]
Closing this, misunderstanding of the scope - see my comment above.
