### ISSUE TITLE
Error pages not used for missing assets

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-assets#211]
When accessing a file that doesn't exist in SS4, you currently get a blank page showing this:

![1](https://user-images.githubusercontent.com/3703500/51960142-c7b44b00-24ab-11e9-92d4-c34e17585950.png)

This is because the following doesn't take the https://github.com/silverstripe/silverstripe-errorpage module into account:

https://github.com/silverstripe/silverstripe-assets/blob/1/src/Flysystem/FlysystemAssetStore.php#L986

Which means you don't get a themed error page.. is this intended? To confirm, you can replace the above with the following:

`Controller::curr()->httpError($code);`

**Comment by chillu** [comment]
Which file are you trying to access? Are you using the public webroot? Apache with `.htaccess` support? `public/assets/.htaccess` might have different behaviour than `public/.htaccess` for example.

**Comment by albanyacademy** [comment]
I'm also experiencing this issue, though its 50/50 this one or a static themed error page _is_ generated, but it fails to update with subsequent theme/requiredfiles changes. public webroot, silverstripe enterprise platform + local windows machine w/ wamp apache.

i've tested with deleting the html file, and it seems just that a) the trigger to actually generate the static page doesn't always work if its not present (needs a combination of dev/build?flush=1 and publishing the sitetree errorpage), and b) if the static page is already present, silverstripe never updates it. Tested on 4.3.x

**Comment by nglasl** [comment]
I'm just closing a few of my old issues that may no longer be applicable. It's possible this one is due to how we're running up projects. If anyone is still hitting this, please open a new issue with version details, how the project was configured, and a link to this.
