### ISSUE TITLE
Flysystem - Storage adapters that use Guzzle PSR7 - error thrown when closing file resource from temp file

### ISSUE THREAD

**Issue by obj63mc** [silverstripe/silverstripe-assets#212]
Affects SS4.x - relates to issue https://github.com/Superbalist/flysystem-google-cloud-storage/issues/95

I am creating a new Flysystem adapter for SS4 that uses google cloud storage, when you upload an image, it is pulling the file from the systems temp directory and then uploading it to google cloud utilizing https://github.com/Superbalist/flysystem-google-cloud-storage/

The issue is that after the file successfully uploads, the temp file is being removed automatically buy Guzzle so when you get to line 260 and 453 the resource stream is no longer valid as the file doesn't exist anymore.

Because of this I am recommending that we wrap the fclose with a check from is_resource first to help catch any errors.  When I set this up, all works as expected.

Steps to reproduce - 
1. Create a new SS site from scratch.
2. You can download my working flysystem adapter from - https://github.com/obj63mc/silverstripe-google-cloud-storage  (run composer install for reqs)  Note this is just the first revision, just place in root of your SS4 site for testing
3. Setup a google cloud storage bucket where all users have read access and your user has admin access
4. Download your access credentials json file and place in the root of the site.
5. Setup your .env file with the following - 
        GC_PROJECT_ID="your google project id"
        GC_BUCKET_NAME="your bucket name"
        GOOGLE_APPLICATION_CREDENTIALS="service-account.json"
6. Run a dev/build and a flush.  
7. Go to /admin/assets and upload a file - 
8. Error message returned - 

		ERROR [Warning]: fclose(): supplied resource is not a valid stream resource
		IN POST /admin/assets/api/createFile
		Line 263 in /Users/joemadden/Sites/ss4-google-cloud-storage/vendor/silverstripe/assets/src/Flysystem/FlysystemAssetStore.php

		Source
		======
		  254:             // Read contents as string into flysystem
		  255:             $handle = fopen($path, 'r');
		  256: 
		  257:             if ($handle === false) {
		  258:                 throw new InvalidArgumentException("$path could not be opened for reading");
		  259:             }
		  260:             $result = $filesystem->putStream($fileID, $handle);
		  261: 
		  262:             //if(is_resource($handle)){
		* 263:                 fclose($handle);
		  264:             //}
		  265:             return $result;
		  266:         };
		  267: 
		  268:         // When saving original filename, generate hash
		  269:         if (!$variant) {

		Trace
		=====
		fclose(Resource id #14)
		FlysystemAssetStore.php:263

		SilverStripe\Assets\Flysystem\FlysystemAssetStore->SilverStripe\Assets\Flysystem\{closure}(League\Flysystem\Filesystem, e49de9993b/download-v10.png)
		FlysystemAssetStore.php:619

		SilverStripe\Assets\Flysystem\FlysystemAssetStore->writeWithCallback(Closure, download.png, e49de9993b52f9362bbfb3965429c6c398194c06, , Array)
		FlysystemAssetStore.php:274

		SilverStripe\Assets\Flysystem\FlysystemAssetStore->setFromLocalFile(/private/var/tmp/phpTwLlKL, download.png, e49de9993b52f9362bbfb3965429c6c398194c06, , Array)
		DBFile.php:216

		SilverStripe\Assets\Storage\DBFile->setFromLocalFile(/private/var/tmp/phpTwLlKL, download.png, , , Array)
		File.php:1135

		SilverStripe\Assets\File->setFromLocalFile(/private/var/tmp/phpTwLlKL, download.png, , , Array)
		Upload.php:233

		SilverStripe\Assets\Upload->storeTempFile(Array, download.png, SilverStripe\Assets\Image)
		Upload.php:204

		SilverStripe\Assets\Upload->loadIntoFile(Array, SilverStripe\Assets\Image, /)
		AssetAdmin.php:323

		SilverStripe\AssetAdmin\Controller\AssetAdmin->apiCreateFile(SilverStripe\Control\HTTPRequest)
		RequestHandler.php:323

		SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, apiCreateFile)
		Controller.php:284

		SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, apiCreateFile)
		RequestHandler.php:202

		SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
		Controller.php:212

		SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
		LeftAndMain.php:763

		SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest)
		AdminRootController.php:123

		SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest)
		Director.php:361

		SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
		VersionedHTTPMiddleware.php:41

		SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		BasicAuthMiddleware.php:68

		SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		AuthenticationMiddleware.php:61

		SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		CanonicalURLMiddleware.php:188

		SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		HTTPCacheControlMiddleware.php:42

		SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		ChangeDetectionMiddleware.php:27

		SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		FlushMiddleware.php:29

		SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		RequestProcessor.php:66

		SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		SessionMiddleware.php:20

		SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		AllowedHostsMiddleware.php:60

		SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		TrustedProxyMiddleware.php:176

		SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		HTTPMiddlewareAware.php:65

		SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
		Director.php:370

		SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
		HTTPApplication.php:48

		SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

		call_user_func(Closure, SilverStripe\Control\HTTPRequest)
		HTTPApplication.php:66

		SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

		call_user_func(Closure, SilverStripe\Control\HTTPRequest)
		ErrorControlChainMiddleware.php:73

		SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain)

		call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain)
		ErrorControlChain.php:235

		SilverStripe\Core\Startup\ErrorControlChain->step()
		ErrorControlChain.php:225

		SilverStripe\Core\Startup\ErrorControlChain->execute()
		ErrorControlChainMiddleware.php:92

		SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
		HTTPMiddlewareAware.php:62

		SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
		HTTPMiddlewareAware.php:65

		SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
		HTTPApplication.php:67

		SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
		HTTPApplication.php:49

		SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
		index.php:25

I'll submit a pull request for this here in a second but wanted to provide a full report of what I was seeing and a way to replicate for now.

**Comment by robbieaverill** [comment]
Fixed with #213 for SilverStripe 5.x, thanks @obj63mc
