### ISSUE TITLE
Migration from SS2/3 to 4 should update Folder records

### ISSUE THREAD

**Issue by gheggie** [silverstripe/silverstripe-assets#215]
When migrating from SS2/3 to 4, existing Folder records will remain in the File table only, assuming no changes to the Folder ORM. However, this doesn't take into account SS4's versioning for Folders, which should always have a corresponding File_Live table record (i.e. Folders are always considered to be published/Live).

The scenario I had: after a migration, a front-end FileField which uploads to the Uploads folder led to a duplicate Uploads folder record being created, because a Live version of the Uploads folder wasn't found. There were other duplicate Folder records created for other folders as well because of this.

https://gist.github.com/gheggie/b2cf93ba38b57b9eadce3e2f29ba8b3b is a task which fixed this issue. Although not perfect, I think some sort of migration task like this should be available by default.

**Comment by wernerkrauss** [comment]
I can confirm this behaviour on a project I upgraded from SS3 to SS4: the folder "Uploads" wasn't published and recreated (with same ParentID), cause it only was in stage table.

Maybe it's a bug in `Folder::find_or_make()`, that it needs to look at the stage table inside a `Versioned::withReadingMode()` statement?

**Comment by dnsl48** [comment]
Issue moved to [silverstripe/silverstripe-upgrader #163](https://github.com/silverstripe/silverstripe-upgrader/issues/163) via [**ZenHub**](https://www.zenhub.com/)
