### ISSUE TITLE
Regorganise file migration task

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#219]
We have been doing lots of file management work lately. This will potentially require projects upgrading from a minor release to 4.4 to take extra step to bring their assets back to the recommended structure.

## Acceptance criteria

* Developers can update to the latest asset structure by running a single unified task, whether they are upgrading from 3.x or a pre-4.4 minor release.
* Unified task performs the following sub tasks:
  * Normalise DB File entries
  * Move files to the appropriate location
  * Find unknown files and adds matching DB entries
  * Generate thumbnails
  * Updates HTMLText references to files so they use short codes
* The unified task works with `legacy_filenames` or `keep_archive_assets` enabled.
* Developers can understand what the unified task does by reading the [File Migration doc](https://docs.silverstripe.org/en/4/developer_guides/files/file_migration/)
* Migration task works with 1000 files and images

## Related issues

* https://github.com/silverstripe/silverstripe-versioned/issues/177
* https://github.com/silverstripe/silverstripe-assets/issues/175
* https://github.com/silverstripe/silverstripe-assets/issues/188
* https://github.com/silverstripeltd/open-sourcerers/issues/45
* https://github.com/silverstripe/silverstripe-framework/issues/8664

## Notes

- Refactor `\SilverStripe\Assets\Flysystem\FlysystemAssetStore::parseFileID` to use file utility class.
- Consider if integration tests are appropriate given the complexity of combining the tasks

**Comment by chillu** [comment]
Relies on https://app.zenhub.com/workspace/o/silverstripe/silverstripe-framework/issues/8924

**Comment by chillu** [comment]
Has been done by implementing the referenced storycards in here.

> Normalise DB File entries
> Move files to the appropriate location

Those two aren't split out into individual tasks, but that's fine - they should always be run together

> Find unknown files and adds matching DB entries

We haven't completed that card, but it's not blocking closing this card here.
