### ISSUE TITLE
Tag 1.3.4 / backport https://github.com/silverstripe/silverstripe-assets/pull/209 

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-assets#229]
Just been bitten hard by https://github.com/silverstripe/silverstripe-assets/pull/209 which doesn't appear in any release yet (as recipe uses ^1.3). Been a couple of months since that patch so good to get an update into CWP releases to save the next developer.

**Comment by ScopeyNZ** [comment]
I can't see why that PR targeted `1`. It's even marked as a patch. Makes sense to backport it imo.

**Comment by robbieaverill** [comment]
Yeah, feel free to backport by hand if you want to @wilr

**Comment by chillu** [comment]
Patch level fixes should be applied to release lines in active development or full support, which is 4.2 and newer as of 1st of April (https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). I've reminded the team about this process :)

@wilr Would you be able to send a backport PR to 1.2, and check that it fixes your issue there?

**Comment by robbieaverill** [comment]
This is tagged now
