### ISSUE TITLE
More memory efficient file looping in migration task

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-assets#243]
Don't create gigabytes of PHP objects through `File::get()` and `Folder::get()` in aspect of `MigrateFileTask` aspects. Potentially review the memory usage numbers we've quote in `File_Migraiotn.md` based on that

**Comment by ScopeyNZ** [comment]
I think it makes a bit of sense to add a method to get a generator from a DataList which will help here:

```diff
--- src/ORM/DataList.php	
+++ src/ORM/DataList.php
@@ -771,6 +771,18 @@
         return $this;
     }
 
+    /**
+     * @return \Generator&DataObject[]
+     */
+    public function getGenerator()
+    {
+        $query = $this->dataQuery->query()->execute();
+
+        while ($row = $query->record()) {
+            yield $this->createDataObject($row);
+        }
+    }
+
     public function debug()
     {
         $val = "<h2>" . static::class . "</h2><ul>";
```

**Comment by chillu** [comment]
I'm not too fussed about generator vs. inlined use, as long as this doesn't block any merges this week. It's a helper class, and unlikely to be subclassed in terms of "clean API surface".

**Comment by ScopeyNZ** [comment]
I did it anyway - I'm not really invested in whether that gets merged or not though: https://github.com/silverstripe/silverstripe-framework/pull/8931

**Comment by unclecheese** [comment]
Closing, as this has been addressed in the merged PR above, as well as in the chunking that @maxime-rainville has added to the relevant task.
