### ISSUE TITLE
Performance of the new File migration is too slow

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#268]
Some users are experiencing slow migration taking 3-4 sec per file.

We need to bring this down.

# Pull Request
* [ ] https://github.com/silverstripe/silverstripe-assets/pull/271

**Comment by maxime-rainville** [comment]
Just made some profile of the migration task. A big part of the job seems to be spent on computing file hashes: 23.76% ... in reality, I think it's closer to 83%, because on my profile spent 71% of its time on `session_start`.

![image](https://user-images.githubusercontent.com/1168676/57745934-46fc2080-7723-11e9-837d-fa90161a8b05.png)

That's 220 calls to move 5 files with 3 variants per file. I'll see if I can add some quick caching mechanism to our Filesystems, so we don't have to recompute the hash all the time.

**Comment by ScopeyNZ** [comment]
> because on my profile spent 71% of its time on session_start

How did you run the profile? I've seen this when running things through apache locally because active sessions are blocking (per session ID). You need to ensure your profiled request is the only running request

**Comment by maxime-rainville** [comment]
I had a Firefox session running on the side. So that must be it.

**Comment by maxime-rainville** [comment]
I had another go at it running on the command line. It looks more like 25% in most cases. It's still the main win I can get. Most of the other time is spend building thumbnails, which I can't really do anything about. That's when working with 3MB images ... generating the hash of smaller files will be a lot less intensive.

**Comment by maxime-rainville** [comment]
Here's my thinking:

* Create a brand new FileHashService whose only purpose is to compute the hash of files on various file system.
* The service will cache values based on two keys: FileSystem and FileID

FlysystemAssetStore and FileIDHelper are the two main class that compute hashes. So those two classes will need to be updated to call ShaOneHashService instead.

There's some complication here, that files can moved arround, overwritten, deleted, move between filesystems. So our cached hashes might be invalidated without our FileHashService picking up on it.

There's a few approach we could take around this:
* only enable caching on file intensive operation where we have good understanding of what is going on ... there could be some performance gain here if we enable this all the time, but I don't want to start testing everything this late in the release process.
* add a timestamp to our cache key. This would involved doing reading the last modified date of each file before returning its cached hash. This would be somewhat slow because it involves a file operation each time you want to read a value, but it would still be a massive improvement over what we have
* Update FlysystemAssetStore to invalidate and set hash value as it performs file operations. 
  * e.g: If we are moving X from the public to protected store, we can just copy the existing hash value from to the new key and invalidate the old one.
  * This won't require any file operation to access a cache value, however it's more complicated to implement and test. And it will only detect a change if it's done directly through the FlysystemAssetStore

We can't pre-populate our cache from the hashes in the DB, because the values will be unset prior to the migration. Plus that would require us to have 100% trust on the integrity of the hashes in the DB.

**Comment by maxime-rainville** [comment]
On a side not, I tried migrating a lot of small files to see where the bottle neck was there.

Main problem there seems to be queries: 3420 request to migrate 100 files, which look like a lot. Once I'm done with the caching, I'll see what we can do there.

**Comment by maxime-rainville** [comment]
I've got a FileHashingService going and all unit tested https://github.com/silverstripe/silverstripe-assets/pull/271

Just need to update `FileIDHelperResolutionStrategy` and `FlysystemAssetStore` to hook into it.
