### ISSUE TITLE
Tests referenced silverstripe/versioned but do not require it

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-assets#27]
[This test class](https://github.com/silverstripe/silverstripe-assets/blob/master/tests/php/AssetControlExtensionTest/VersionedObject.php#L20-L24) uses versioned, but composer doesn't require it.

Travis will be passing because it's required manually from the Travis configuration.

This is causing problems like this: https://travis-ci.org/silverstripe/silverstripe-tagfield/jobs/245966412

```
1) SilverStripe\TagField\Tests\StringTagFieldTest
InvalidArgumentException: silverstripe\assets\tests\assetcontrolextensiontest\versionedobject references nonexistent SilverStripe\Versioned\Versioned in 'extensions'
```

**Comment by dhensby** [comment]
@tractorcow I think the problem here is that the `Extensible` trait and the `ExtensionMiddleware` are too opinionated about whether extension classes exist for tests to be able to run with or without optional modules.

Any ideas of ways around this?

**Comment by tractorcow** [comment]
I'd add versioned to require-dev to get around this issue, to declare that although the module itself doesn't require versioned, it is expected to be installed for tests.

If you add an extension that doesn't exist the error should surface, as it has.

**Comment by robbieaverill** [comment]
It's already a dev dependency here as of 0a779e8923df84959f4f70770113b1bd4aded4f6, which was there at the time that example Travis job failed - it didn't install silverstripe/versioned at the time.

**Comment by dhensby** [comment]
I think this can be closed - there's no other way to fix this problem than what we've done.

The ideal solution is to have a way of adding extensions in tests only and not killing an entire build if the extension is there - that's an issue for `framework` and one that may never be addressed as killing the system is intended, it seems :(
