### ISSUE TITLE
Inordinate amount of File Hash computing with new File Resolution strategy

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#279]
Our new File Resolution Strategy currently computes the hash of files multiple times on each request.

For example, when listing the content of Folder in asset-admin, these 11 calls will trigger file hash computing for each individual file:
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::getSourceURL()
* SilverStripe\\Assets\\Storage\\DBFile::getSourceURL()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::exists()
* SilverStripe\\Assets\\Storage\\DBFile::getMetaData()

This is prohibitively expansive, especially for large file.

We need to investigate a way to avoid computing hashes for all those method. This might involve being more trusting of the hash as read from the fileID.

# Pull Requests

* [x] https://github.com/silverstripe/silverstripe-assets/pull/282
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9045

**Comment by maxime-rainville** [comment]
For reference, I use this ugly method to figure out where all those calls are coming from.
```php
private function spitStack()
{
    $stack = debug_backtrace();
    $items = [];

    while (!empty($stack)) {
        $item = array_shift($stack);
        if (isset($item['class']) && $item['class'] == FlysystemAssetStore::class) {
            break;
        }
    }

    while (!empty($stack)) {
        $item = array_shift($stack);
        $items[] = $item;
        if (!isset($item['class']) || $item['class'] != FlysystemAssetStore::class) {
            break;
        }
    }


    
    $output = $_SERVER['REQUEST_URI'];
    error_log($output);
    foreach ($items as $item) {
        $args = isset($item['args']) ?
            array_reduce($item['args'], function ($init, $arg) {
                return $init . (
                    is_scalar($arg) ? $arg : gettype($arg)
                    ) . ', ';
            }, '') : '';
        error_log(sprintf("    %s::%s(%s)",
            isset($item['class']) ? $item['class'] : '',
            isset($item['function']) ? $item['function'] : '',
            $args
        ));
    }
}
```

**Comment by chillu** [comment]
We just need to make it work like 4.3. Specifically, identify the places where 4.3 used hashing (only writes?), and limit the new 4.4 implementation to those usages.

**Comment by maxime-rainville** [comment]
> We just need to make it work like 4.3. Specifically, identify the places where 4.3 used hashing (only writes?), and limit the new 4.4 implementation to those usages.

It doesn't work this way. Pretty much all the methods on AssetStore use hashes. From the AssetStore's perspective the hash, is part of the identifier.

This worked OK in SS4.3 because we could get a partial hash from the FileID all the time. Now we can only get the hash from the FileID on the protected store. On the public store, there's no way of knowing the hash without computing it.

The `legacy_filename` mode got around this by accepting that it would sometimes get lies back from the `AssetStore` ... that's probably why important features are broken when using `legacy_filenames` https://github.com/silverstripe/silverstripe-framework/issues/8867.

# Possible solution

We could implement some soft version of `applyToFileOnFilesystem` that will always resolve if a File is found at the expected location even if we can't find the FileHash. Right now, we always start by looking at the public store and then the protected store. We probably want to reverse that ... that will minimise the scenarios where we return false data.

# When will AssetStore be lying

If we check the public store first, AssetStore will return false data under these conditions:
* Whenever you asking for info about a protected file with public file version. (pretty much all the time)

If we check the protected store first, AssetStore will return false data under these conditions:
* You are asking for info about a file that has been deleted (or superseded by a different version) and a newer version if available on the public store.
* You've migrated from a system that had `legacy_filenames` enabled, didn't run the file migration task, and you want info about a protected file

There's probably more esoteric scenarios I could imagine, but those are relatively common ones that comes to mind.

# Which method would use the softer resolution
* exists
* getVisibility
* getAsStream
* getAsString
* getAsURL
* grant
* revoke
* canView
* getMetadata
* getMimeType

# Which method would use the harder resolution
* setFromLocalFile
* setFromString
* setFromStream
* delete
* rename
* copy
* normalise
* publish
* swapPublish
* protected

**Comment by maxime-rainville** [comment]
Here's some benchmark on the performance of SS4.4 with/without caching https://docs.google.com/spreadsheets/d/1YI5JG6OqIKi9eFX44SKVIYgEQZbCg9ND5ASf3wgR8wA/edit?usp=sharing

**Comment by maxime-rainville** [comment]
I did a PR that enables caching all the time and makes it persistent https://github.com/silverstripe/silverstripe-assets/pull/282

**Comment by maxime-rainville** [comment]
Outstanding points are covered by https://github.com/silverstripe/silverstripe-assets/issues/288****
