### ISSUE TITLE
4.4.1 update breaks importing of images

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-assets#292]
Since the 4.4.1 update, the images, that i import trough tasks, are not handeling the thumbnail or image generation correctly anymore.

For example, after an import i get this result in the filesystem:

![Screenshot 2019-06-14 at 18 09 03](https://user-images.githubusercontent.com/1334195/59523576-f880a400-8ed1-11e9-8bb9-90999b493cf5.png)

When i open one of the images it shows a preview in the sidebar:

![Screenshot 2019-06-14 at 18 09 13](https://user-images.githubusercontent.com/1334195/59523643-1a7a2680-8ed2-11e9-995a-0f47eab16f9c.png)

When i then publish the image it says the image could not be found:

![Screenshot 2019-06-14 at 18 09 26](https://user-images.githubusercontent.com/1334195/59523680-3087e700-8ed2-11e9-81c9-5567783b149a.png)

After running the MigrateFileTask the thumbnails are shown in the overview and sidebar. But when i publish one of the files it says the image could not be found again.

![Screenshot 2019-06-14 at 18 10 55](https://user-images.githubusercontent.com/1334195/59523742-5e6d2b80-8ed2-11e9-8caa-31d9d42531aa.png)

Either i have an import that is not compatible with the 4.4.1 way of storing images, what i can understand, or there is a bug in the new thumbnail/image system.

This is the method i use for downloading an image file, the method is in a class extending on the `Image` class. So `$this` is an instance of `Image` and the `Client` is a Guzzle client.
```php
private function downloadImage($src, $folder)
{
    $client = new Client(['http_errors' => false]);
    $request = $client->request('GET', $src);
    $folder = Folder::find_or_make($folder);
    $sourcePath = pathinfo($src);
    $fileName = explode('?', $sourcePath['basename'])[0];
    $this->setFromString($request->getBody()->getContents(), $fileName);
    $this->ParentID = $folder->ID;
    $this->OwnerID = ($user = Security::getCurrentUser()) ? $user->ID : 0;
    $this->publishFile();
}
```
The method gets called on [this line](https://github.com/xddesigners/silverstripe-shopify/blob/master/src/model/Image.php#L87) in my module

I would like to know if this is an issue in the new filesystem, and if there is any way i could help in finding the issue. Or that i have changes to make to my modules that import images. If that is the case i would appreciate some pointers in what direction i should look.

If you need more information, or if there is anything i could do let me know!

Cheers!

**Comment by maxime-rainville** [comment]
I tried running your your `downloadImage()` locally on 4.3 and 4.4. I got the same result in both cases:
* no thumbnail,
* publishing the image seems to work fine.

It might have something to do with the context in which you call the image that's different from mine, but without setting up your module locally (FYI it looks pretty cool) and setting up a Shopify site for me to test it's hard to say.

# Debugging this issue
If you can try the following step that could help me debug the issue:
* After you call `downloadImage`, what files are actually created in your protected store (`assets/.protected/`) and your public store (`assets/`)
* After you publish one of those images that got imported with `downloadImage`, what happens to those files that you saw in the previous step.

Also, did you have `legacy_filenames` enabled on your SilverStripe 4.3 install?

# Possible point of note
Here's a couple things you could look at:
* `setFromString()` use to save the file in the public store by default ... which was kind of weird, because you create a new image and the physical file would be publicly available until you call write() which move the file to the protected store. `setFromString()` now saves the physical file to the protected store by default.
* `publishFile` doesn't interact with `Versioned` at all. It just moves the physical file from the protected store to the public store. Unless you are actively trying to bypass the regular `Versioned` behavior, you should avoid calling it. Call `publishSingle` or publishRecursive` instead.

The asset-admin thumbnails are normally generated automatically when you upload the file initially through the UI. Since you are bypassing the UI, you will need to generate those yourself. You can use this code snippet.
```php
$assetAdmin = AssetAdmin::singleton();
$img->FitMax(
    $assetAdmin->config()->get('thumbnail_width'),
    $assetAdmin->config()->get('thumbnail_height')
);
$img->FitMax(
    UploadField::config()->uninherited('thumbnail_width'),
    UploadField::config()->uninherited('thumbnail_height')
);
```

On a side note, you might want to try to replace your `setFromString` call with a `setFromStream` instead. It's not going to have any impact on your current situation, it's just better when dealing with big files. You should be able to get a resource stream out of guzzle.

Feel free to hit me up on the SilverStripe community slack.

**Comment by TheBnl** [comment]
Hi Maxime,

Thank you for looking into this! I have a similar download setup with a Instagram module i've made, i currently use that one for debugging. 

I also don't get the thumbnail in 4.3, but a thumbnail becomes available after a save and the file is correctly available on the front-end as well. This is fixed by adding a `generateThumbnails` method as you've suggested. But on 4.4 the issue with the files not being found still persists.

I've changed the download method to use the stream resource and removed the `publishFile` call, as you suggested, also `legacy_filenames` has never "consciously" been enabled or disabled.
```php
public function downloadImage()
{
    $client = new Client(['http_errors' => false]);
    $folder = Folder::find_or_make($this->uploadFolder());
    $imageSource = $this->InstagramImageURL;
    $sourcePath = pathinfo($imageSource);
    $fileName = explode('?', $sourcePath['basename'])[0];
    $request = $client->request('GET', $imageSource);
    $stream = $request->getBody();

    if ($stream->isReadable()) {
        $this->setFromStream($stream->detach(), $fileName);
        $this->ParentID = $folder->ID;
        $this->OwnerID = $this->findOwnerID();
    } else {
        throw new \Exception("Error while downloading file: $imageSource");
    }
}
```

The task calls the method here:
```php
private static function handleObject(array $data) {
    // Find or make a facebook image object from the given facebook id
    $mediaObject = InstagramMediaObject::find_or_make($data['id']);

    // Loop over the data and set like the mapping
    self::loopMap($mediaObject, $data, self::config()->get('data_mapping'));

    try {
        if ($mediaObject->isChanged('InstagramImageURL', DataObject::CHANGE_VALUE)) {
            $mediaObject->downloadImage();
            // $mediaObject->generateThumbnails();
        }

        if ($mediaObject->isChanged()) {
            $mediaObject->write();
            // have to generate the thumbnails after a write
            $mediaObject->generateThumbnails();
        }

        if (!$mediaObject->isLiveVersion()) {
            $mediaObject->publishSingle();
        }
    } catch (\Exception $e) {
        echo "[ERROR] {$e->getMessage()} \n";
    }

    return $mediaObject;
}
```

This results in the following asset folder structure, and files UI:

![Schermafbeelding 2019-06-17 om 15 02 52](https://user-images.githubusercontent.com/1334195/59606296-096b2880-9111-11e9-8cab-9254b0d69eac.png)

![Schermafbeelding 2019-06-17 om 13 38 07](https://user-images.githubusercontent.com/1334195/59606066-84800f00-9110-11e9-8143-32c76356c52f.png)

Saving or publishing the files doesn't change any files.

Funny thing is, when i comment out `$mediaObject->publishSingle();` i get the following results.

![Schermafbeelding 2019-06-17 om 15 04 18](https://user-images.githubusercontent.com/1334195/59606393-4d5e2d80-9111-11e9-956b-95e418d5ae10.png)

All the files are in the protected folder, tho they are both in the root and in a protected instagram subfolder.

![Schermafbeelding 2019-06-17 om 15 04 49](https://user-images.githubusercontent.com/1334195/59606398-50591e00-9111-11e9-894b-1993386ccab6.png)

All the thumbnails are correctly shown in the UI, but when i publish one of the files:

![Schermafbeelding 2019-06-17 om 15 06 54](https://user-images.githubusercontent.com/1334195/59606568-bfcf0d80-9111-11e9-9cfb-5d81e446c4b6.png)

But the file seems to be moved correctly from the protected to the public folder, with thumbnails and all.

![Schermafbeelding 2019-06-17 om 15 07 26](https://user-images.githubusercontent.com/1334195/59606595-d5443780-9111-11e9-8fc8-9c4f516e7c1f.png)

If you want i can invite you to my Instagram sandbox (that's probably easier to test locally then to setup an Shopify store 😉) and give you keys to install the module. If you can send an email to bram@xd.nl, i'll reply with the info.

**Comment by RVXD** [comment]
This simple test seems to work fine with 4.4
It downloads the google logo, puts it in a new folder and publishes the file and generates thumbnails.

```
public function imagetest(){
        // download image
        $client = new Client(['http_errors' => false]);
        $folder = Folder::find_or_make('imagetest');
        $imageSource = 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png';
        $sourcePath = pathinfo($imageSource);
        $fileName = explode('?', $sourcePath['basename'])[0];
        $request = $client->request('GET', $imageSource);
        $stream = $request->getBody();

        $image = new Image();

        if ($stream->isReadable()) {
            $image->setFromStream($stream->detach(), $fileName);
            $image->ParentID = $folder->ID;
            $member = Security::getCurrentUser();
            if ($member) {
                $image->OwnerID = $member->ID;
            }

            // store image
            $image->write();

            // create thumbs
            $assetAdmin = AssetAdmin::singleton();
            $image->FitMax(
                $assetAdmin->config()->get('thumbnail_width'),
                $assetAdmin->config()->get('thumbnail_height')
            );
            $image->FitMax(
                UploadField::config()->uninherited('thumbnail_width'),
                UploadField::config()->uninherited('thumbnail_height')
            );

            // publish image
            $image->publishSingle();

            return $image;

        } else {
            throw new \Exception("Error while downloading file: $imageSource");
        }

    }
```

Result:
![Screenshot 2019-06-18 at 09 09 00](https://user-images.githubusercontent.com/1586761/59660441-d1172900-91a8-11e9-941c-23d6dc153bde.png)

**Comment by TheBnl** [comment]
Alright, so we've narrowed down the issue and i think we can close this one. 

It is a headache of a problem to debug and i don't think i'm able to communicate this clearly but here it goes.. 😜

We've tried importing images trough tasks, plain old controller actions, stripping everything down to the bare bones, like the method described above, and the one constant in this issue was the use of a **numeric** folder name that was set by an imported id from the used service.

For example adding an "X" after the id as folder name e.g. "1234X" makes everything work as expected whereas just the id "1234" breaks the whole folder and its contents as show in the screenshots above.

But this causes only problems when using the imported id as folder name. So when the exact same folder is created manually `Folder::find_or_make('base/1234');` everything works fine. 

The fix i'm using now is to simply use a sting named folder (though i converted the numeric id to a string as well..), no problems occur with using the "username" as a folder.

So i'm going to close this issue as i think it's due to the encoding of the imported id, but i honestly cannot find out what or why tho.. the mystery remains..

**Comment by maxime-rainville** [comment]
I'll reopen because having a number as folder name shouldn't break things.

**Comment by chillu** [comment]
> I'll reopen because having a number as folder name shouldn't break things.

Should this be tracked as a separate ticket?

**Comment by maxime-rainville** [comment]
I haven't confirmed it yet. I'll open a new ticket if/when I do.

**Comment by maxime-rainville** [comment]
Confirmed the problem and raise a separate issue https://github.com/silverstripe/silverstripe-assets/issues/300
