### ISSUE TITLE
After downgrade 4.4 to 4.3 all images not found

### ISSUE THREAD

**Issue by RVXD** [silverstripe/silverstripe-assets#293]
Upgraded to 4.4 but decided to downgrade to 4.3 because of issues. After downgrade to 4.3.5 All images are missing, see screenshot, is there a way to restore these?

![Screenshot 2019-06-17 at 17 42 15](https://user-images.githubusercontent.com/1586761/59618180-f6b01e00-9127-11e9-997d-02b4fe5defd3.png)

**Comment by chillu** [comment]
No sorry, you'll have to restore from your backups taken before the upgrade, we don't provide downgrade paths
