### ISSUE TITLE
FileIDHelperResolutionStrategy uses allVersions() which is removed in 5.0

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-assets#294]
This is my fault for not correctly deprecating those methods in the 4.x line, but some of the new asset migration code uses `Versioned::allVersions()` which is removed in 5.x.

It needs to be updated to use `::Versions()` and not pass arguments - it returns a DataList that can be filtered afterwards.

Not noticed until now because the module branches 1 -> master were not merged up.

Example build failure: https://travis-ci.org/silverstripe/silverstripe-assets/jobs/547065582

Side note: here are the missing deprecation warnings added to versioned https://github.com/silverstripe/silverstripe-versioned/pull/238

**Comment by dhensby** [comment]
fixed by #383
