### ISSUE TITLE
The build task "TagsToShortcodeTask" could not be found

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-assets#295]
This is either a documentation bug or a bug in this module, and I'm not sure which.

In the upgrade guide (https://docs.silverstripe.org/en/4/upgrading/upgrading_project/#tagtoshortcode) the command listed is: `./vendor/bin/sake dev/tasks/TagsToShortcodeTask`

This results in the below error, despite the build task existing:
```The build task "TagsToShortcodeTask" could not be found```

It took me a while to find it, but the reason for this is that the build task includes this:

```php
private static $segment = 'TagsToShortcode';
```

meaning that the correct magic command to invoke is actually: `./vendor/bin/sake dev/tasks/TagsToShortcode` (note the lack of 'Task' suffix).

I would argue that the best thing to do here is to update the module to either remove the segment or change it, because every other task has a suffix of `Task`, but that will probably break semantic versioning whereas updating the docs won't...

# Pull Request
- [x] https://github.com/silverstripe/silverstripe-assets/pull/297

**Comment by robbieaverill** [comment]
Agreed, safest to treat this as a documentation change. Since it's a migration task, I doubt it'll be that highly used (at least day-to-day) so if you did want to change the segment I think it'd be OK to do so.

**Comment by chillu** [comment]
Andre decided to change the segment, and I don't have any gripes with that
