### ISSUE TITLE
Division by zero in dependency intervention/image

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-assets#296]
intervention/image divides by zero when scaling long, narrow images with small height (as when SilverStripe creates a thumbnail). The dependency is stated as intervention/image (^2.3) but this bug has been patched as of 2.4.3. See https://github.com/Intervention/image/pull/887/files

At present, when a user uploads such a file, the thumbnail generation fails. This also crashes SilverStripe 4 migrations.

**Comment by robbieaverill** [comment]
That constraint should allow you to install the version you've mentioned. Does it work if you `composer update intervention/image`?

**Comment by chillu** [comment]
@oddnoc Good catch, wanna send a PR to update intervention?

**Comment by oddnoc** [comment]
> @oddnoc Good catch, wanna send a PR to update intervention?

> That constraint should allow you to install the version you've mentioned. Does it work if you `composer update intervention/image`?

Quite. It turns out that they did patch this about 3 weeks ago, but Packagist has not yet picked up the tag. My colleague has [alerted](https://github.com/Intervention/image/issues/954) Intervention.

As a workaround, a project can add the GitHub url for intervention/image as a repository entry in composer.json.

As this is not a bug in this module, I'm closing this issue.
