### ISSUE TITLE
Upgrading existing site from 4.3 to 4.4 results in missing files

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-assets#299]
I recently (24th of June) upgraded an existing site from 4.3.0 to 4.4.1 initially everything looked good so i assumed the upgrade was a succes. 

After reading in on the [docs](https://docs.silverstripe.org/en/4/developer_guides/files/file_migration/#migrating-from-silverstripe-4-3-or-below-to-silverstripe-4-4-or-above) about the file migration, i figured i didn't had to run the migration task "No, you do not need to run the file migration task when upgrading to SilverStripe 4.4 or later." So i was pretty confidently moving on to the next project.

But after three days, i get a message that files where not showing up. Looking into this i presumed it was due to the new filesystem that came with 4.4.1 so i made a backup of the database and ran the `FileMigrationTask`. This resulted in a log with a lot of warnings:
```
[2019-06-27 13:39:18] log.NOTICE: Step 2/2: Migrate files in <4.4 format to new format
[2019-06-27 13:39:19] log.INFO: Migrating files in the "live" stage
[2019-06-27 13:39:19] log.WARNING:   Can not migrate Uploads/IMG_0550.jpg / d030bdb468cfdb6903502479005d3165d6c07ae2 because it does not exist on the "live" stage
...
[2019-06-27 13:39:19] log.WARNING:   Can not migrate Uploads/sponsor3.jpg / 99c458b36252c261a0376299a57e1f221d8135b0 because it does not exist on the "live" stage
[2019-06-27 13:39:23] log.INFO: Migrated 115 files in the "live" stage
[2019-06-27 13:39:23] log.INFO: Migrating files in the "draft" stage
[2019-06-27 13:39:23] log.WARNING:   Can not migrate Uploads/IMG_0550.jpg / d030bdb468cfdb6903502479005d3165d6c07ae2 because it does not exist on the "draft" stage
...
[2019-06-27 13:39:28] log.WARNING:   Can not migrate gallery/FotoBjorn03-klein-website.jpg / 850ea2715648422c82e06a4a0b7f2bf929082d6b because it does not exist on the "draft" stage
[2019-06-27 13:39:28] log.INFO: No files required migrating in the "draft" stage
```

There are 418 files in the File table, so the message `Migrated 115 files in the "live" stage` and `No files required migrating in the "draft" stage` didn't really get my hopes up 😬

Also the erroneous files mentioned in the log could not be found in the physical file system, this is what got me worried most, where did the actual files go?

For now i restored a backup from before the update and restored the database from before i ran the file migration so the data is up to date. This has restored everything as far as i can tell at the moment. 

I'm going to look into what could have happend in the 3 days the update was live, maybe the problem lies with editors editing pages and triggering actions in the filesystem.

**Comment by maxime-rainville** [comment]
Can you confirm the file actually exists? Also, can you confirm if your 4.3 install was using `legacy_filenames`?

**Comment by TheBnl** [comment]
When I was notified about the missing files I first ran the migration task, after I read the log I searched for the files but I couldn't find these on the system. After I reverted to the backup all the files where restored. 

`legacy_filenames` was not set my projects config.

The project was created on SS version 4.2.1

**Comment by maxime-rainville** [comment]
Can you rerun the file migration again in a separate environment and see if you end up with missing files again?

If you you end up with missing files, can you send us a sample of file paths that went missing?

**Comment by aletail** [comment]
Just to chime in, I had a similar issue
- Upgrading from 4.2.x to 4.4.1
- The file migration had a list of images with this warning:
> Can not migrate ProductImages/HaloPro_613-v2.jpg / 9d9f3c1080501bb2e8ccbff1632603d3d56188f2 because it does not exist on the "live" stage
> Can not migrate ProductImages/HaloPro_613-v2.jpg / 9d9f3c1080501bb2e8ccbff1632603d3d56188f2 because it does not exist on the "draft" stage
- The images were not removed from the file system, but the cms and front end uses were broken (file not found)
- I could directly access the file /assets/ProductImages/HaloPro_613-v2.jpg which would redirect to ProductImages/[hash]/HaloPro_613-v2.jpg
- There were other images that had no issues being migrated, it was only certain images

I plan to attempt more testing locally when i have the time.

**Comment by maxime-rainville** [comment]
Humm ... The error message would be coming from this line https://github.com/silverstripe/silverstripe-assets/blob/6425852a19e8a69651c8faf832aac51eedd11a93/src/Dev/Tasks/FileMigrationHelper.php#L469

That would imply that there was a File entry in the database but that the `FileMigrationHelper::normaliseAllFiles()` entry couldn't find it.

When you have another go at it, maybe:
* manually confirm what the sha1 hash of that specific file is
* check what was the physical path of the file prior to migration.

**Comment by aletail** [comment]
This is from a different example, but same issue (Upgrading from 4.3.x to 4.4.x)
> manually confirm what the sha1 hash of that specific file is

Is this the FileHash in the database? if so that is: ba61478e7e32cfe0cd39886f32a68a3913fd54f5

> check what was the physical path of the file prior to migration

assets/CaseStudyBackgroundImages/ba61478e7e/case-study-FPO.jpg

Attached a copy of the full migration: [werkbot-migration-log.txt](https://github.com/silverstripe/silverstripe-assets/files/3585657/werkbot-migration-log.txt)

**Comment by maxime-rainville** [comment]
What kind of environment are you running this on? Is it a multi-server set up?

Thinking it could be related to https://github.com/silverstripe/silverstripe-assets/issues/336

**Comment by aletail** [comment]
Local environment, with multiple environments setup (vagrant, xampp, etc...)

I will test with #337  to see if that associated PR fixes the issue.

**Comment by TheBnl** [comment]
I had the issue on a Plesk server:

Plesk Onyx v17.8.11_build1708180301.19 os_CentOS 7
CentOS Linux 7.4.1708 (Core)

The site was running in it's own webspace (not sure what you mean with a multi-server setup). But the Plesk server hosts multiple sites.

**Comment by aletail** [comment]
I tested this with another case of 4.3 to 4.4 using #337 and it did indeed fix the issue.

**Comment by maxime-rainville** [comment]
SS4.4 introduce a new caching service that stores the hash of each file. When you do operation on physical files through the SilverStripe that causes the hash to change, the cache for that specific files gets invalidated.

However, if you are running in environment where one website has multiple copies of that cache (e.g.: because the site is hosted behind a load balancer that dispatches requests to many servers), you might only invalidate one instance of the cache. So the values that had not been invalidated would get confused.

That's what #337 fixed.

Following @aletail's comment, I'll close this issue. But if the problem reoccurs, shout out and I'll reopen.
