### ISSUE TITLE
 FileMigrationHelper: Migration of files with dash (-) in the path

### ISSUE THREAD

**Issue by ichaber** [silverstripe/silverstripe-assets#307]
When migrating files that have a path with a dash in the file path, they will not be migrated although no error is produced.
An example is a file with the following properties:
- ID: 150100
- ClassName: SilverStripe\Assets\File
- Created: 1970-01-01 09:28:24
- LastEdited: 1970-01-01 09:32:30
- Name: Ready-self-check.pdf
- Title: Ready self check
- Filename: assets/Ready/Private-Resources/Ready-self-check.pdf
- Content: NULL
- ShowInSearch: 0
- CanViewType: Inherit
- ParentID: 120536
- OwnerID: 111
- CurrentVersionID: 94500
- SubsiteID: 2
- FileContentCache: NULL
- Version: 0
- CanEditType: Inherit
- FileHash: NULL
- FileFilename: NULL
- FileVariant: NULL

Observe, that the `FileHash` and `FileFilename` are empty although the migration has been completed 'successfully'.

My initial assumption was that the permission in the file system might be wrong, but that does not seem to be the case as other files in other folders have the same permissions and got migrated.

**Comment by chillu** [comment]
Does the `Ready` parent folder have `CanEditType` or `CanViewType` set to something that's not `Inherit`?

**Comment by ichaber** [comment]
All of the parent folders up the chain of `Ready` have `CanEditType` and `CanViewType` set to `Inherit`.
That means they should inherit from root (ID=0).

**Comment by chillu** [comment]
This is a mystery to me, it's such a common use case - and throughout the 4.4 changes to file migration, I've always peer reviewed this by migrating files with dashes (see https://github.com/silverstripe/silverstripe-frameworktest/blob/master/code/tasks/FTFileMakerTask.php#L42)

**Comment by maxime-rainville** [comment]
I sincerely doubt the problem is with the dash. I'll try creating a dummy file locally with the same name and path, just to be sure.

I see you have subsite installed there. Do you have secure assets as well ... or other asset related modules?

**Comment by chillu** [comment]
This turned out to be something completely different: Subsite filtering. Talked to Charlie, this is resolved now.

**Comment by ichaber** [comment]
For the benefit of everyone who tries to extend the MigrateFileTask and for context, this was related to overloading of the MigrateFileTask in the configuration of the Subsites: https://github.com/silverstripe/silverstripe-subsites/blob/e73d622bdbd09b552ac2a0144459f73b97fbf252/_config/middleware.yml#L11-L12

That disabled the filtering for a specific subsite in the `augmentSQL` in https://github.com/silverstripe/silverstripe-subsites/blob/e73d622bdbd09b552ac2a0144459f73b97fbf252/src/Extensions/FileSubsites.php#L75. If the class is not overloaded, that causes the filter to apply and the extended Migration task therefore only migrates files in the _current_ subsite.

An easy fix for that is to disable the Subsite filter in the data query param. Something on the lines of:

```
        $query = parent::getFileQuery();
        if (class_exists(FileSubsites::class) && File::has_extension(FileSubsites::class)) {
            $query = $query->setDataQueryParam('Subsite.filter', false);
        }
```
