### ISSUE TITLE
FileHash not invalidated accross multiple servers

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#336]
# Description
If you're operating in an environment where you have multiple servers, it's possible that he FileHash cache won't be invalidated when you replace a file if that cache is not shared accross all servers.

This leads to weird intermittent behaviour, where files occasionally appear has missing when you hit a server with a stale file hash.

# Possible fix

A simple fix could be to incorporate the file time stamp in the hash key which can be read from the file system and should be touch whenever the physical file is updated. This could have a small performance hit, but retrieving a file timestamp should be a relative quick operation in most situation.

# Pull requests
* [ ]  https://github.com/silverstripe/silverstripe-assets/pull/337

**Comment by adrhumphreys** [comment]
I think the PR should be accepted and then a better solution should be added at a later date. Users whom are upgrading assets are doing so to use the new hashless feature with the idea that they want to retain URL's for assets. This breaks this.

Sure the case can be made that this only occurs on a multi-server setup but that as far as I know is a supported set up for SilverStripe which this is breaking. Either that or I'd expect a warning of some sort to be added to advise users

**Comment by maxime-rainville** [comment]
I don't think this is a very difficult issue to fix. It's probably worth taking an extra day or two to think it thoroughly and come up with long term fix.

**Comment by NightJar** [comment]
Nice work team @adrhumphreys @maxime-rainville :)
