### ISSUE TITLE
Batch "Publish" option doesn't appear for "Modified" files

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-assets#370]
When you select multiple "draft" files, a batch "Publish" option is available in the "more" menu at the bottom of the screen, allowing you to publish all the files at once.

However, for some reason, this "Publish" option doesn't appear for files which are marked as "modified", despite it being a legitimate action.

This is particularly annoying when batch moving multiple files into a folder (or renaming a folder #252) as you then have to manually Publish each one individually.

Can the batch "Publish" option be made available for "modified" files?

_Reproduced in v4.5.0_

# Pull requests
* [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/1057

**Comment by maxime-rainville** [comment]
Confirmed on 4.6.

**Comment by maxime-rainville** [comment]
Easy fix https://github.com/silverstripe/silverstripe-asset-admin/pull/1057
