### ISSUE TITLE
Backslash in file name lead to folders in Hash folder

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#380]
# Description
If you programmatically create a file with a backslash in the filename, assets get confused and tries to create a folder inside the hash folder.

# Steps to reproduce
* Make a call like this `$file->setFromString('hello', 'BadFolder\test.txt');`

Expected results: 
* Either an exception is thrown or 
* ideally all the `\` symbols get swapped for a `/` and the file is saved at `assets/.protected/BadFolder/[hash]/test.txt`

Actual results: No warning are and the file is saved at `assets/.protected/[hash]/BadFolder/test.txt`

# Pull requests
* [ ] https://github.com/silverstripe/silverstripe-assets/pull/381

**Comment by emteknetnz** [comment]
PR's welcome ;-)

**Comment by maxime-rainville** [comment]
Got a PR: https://github.com/silverstripe/silverstripe-assets/pull/381

I don't think think this is a high impact bug. If you're putting backslashes in your filename, you are misusing our the asset system. It's more like a convenience enhencement. So I've only fixed for the next minor.

**Comment by brynwhyman** [comment]
Is this good to close with #381 ? :)

**Comment by emteknetnz** [comment]
^ Yup, PR was merged, can close issue
