### ISSUE TITLE
Re-enable coverage test in travis build

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#389]
We had to disabled the coverage test in https://github.com/silverstripe/silverstripe-assets/commit/12ea7cd2037bebcb3196dd5e3aaa72e6dbc7c7b2 because Travis was running out of memory.

Apparently there's a way to get around this, but we were more concerned with getting the security patch out the door than test coverage. We would like to re-enable this now.

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-assets/pull/390

**Comment by emteknetnz** [comment]
The linked pull request was merged
