### ISSUE TITLE
Mysterious issue in travis

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-assets#408]
PHP: 7.2
DB=PGSQL RECIPE_VERSION=4.6.x-dev PHPUNIT_COVERAGE_TEST=1

![image](https://user-images.githubusercontent.com/4809037/85627741-20990a80-b6c3-11ea-89d1-528fe0a4ad8f.png)

https://travis-ci.org/github/silverstripe/silverstripe-assets/jobs/701477347

As part of this pull request, which updated the `.travis.yml` file
https://github.com/silverstripe/silverstripe-assets/pull/407

It may be one of the following:
- postgres
- PHPUNIT_COVERAGE_TEST
- PHP 7.2
- something else

Recommended approach is isolating what is causing the issue is to create a branch with the same `.travis.yml` file as the pull request, and try changing PGSQL to MYSQL to see if isolates issue, otherwise switch PHPUNIT_COVERAGE_TEST to PHPUNIT_TEST.  Finally change PHP 7.2 to PHP 7.3

**Comment by dnsl48** [comment]
Cannot reproduce. Looks like the build is green now.

**Comment by dnsl48** [comment]
The problem is test coverage takes too long. Took about 50 minutes on my localhost. Some tests there takes longer than 10 minutes, that breaks the build.

**Comment by emteknetnz** [comment]
That's really weird though it makes sense.  Was your local running postgres as well?

**Comment by dnsl48** [comment]
I suspect we might have turned it off in `1.5` for that particular reason ([12ea7cd2](https://github.com/silverstripe/silverstripe-assets/commit/12ea7cd2#diff-354f30a63fb0907d4ad57269548329e3R20))

**Comment by emteknetnz** [comment]
Well, we should probably still do the coverage tests just to be consistent with the other modules, though you could argue that no one really pays attention to codecov and we merge stuff that fails codecov, so..

Maybe just turn it off for now, put an inline comment in the travis config file explaining why it's off and create a new issue to split long running tests and renable codecov
