### ISSUE TITLE
Files can't be published, recursive listContents causes out of memory

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-assets#414]
We found that when trying to publish an image (DataObject) that had it's file replaced the request would timeout and the file would not be replaced. The image (DataObject) would not be updated with the new file.

We were able to trace through the code to find where this was occurring. When you publish a new file, first a call is made to `AssetControlExtension::deleteAll` to delete the existing variants of that file. This loops over all assets passed to it and calls `delete` on the `AssetStore`.

The `AssetStore` is `FlysystemAssetStore`. In the delete code it calls `deleteFromFileStore` to delete the files from the file system. The strategy which is used is the `SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy` and `findVariants` is called on it.

In `FileIDHelperResolutionStrategy::findVariants` it first gets the helpers that are resolvable and then loops through those helpers to try and find the variants. At the begging of these helpers it first calls `$filesystem->listContents($folder, true)`. This translates to `League\Flysystem\Adapter\Local::listContents`.

This function will then recursively list the directories and files based on the directory that is passed through to it. While looping through that directory it will get the meta information for each file.

Usually at this point you will slowly be building a large array and get an exception like:
```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/mysite/releases/046d2d2565825741941ddfa598701a937f48dafd/vendor/league/flysystem/src/Adapter/Local.php on line 508
```

From my understanding we shouldn't be [recursively searching](https://github.com/silverstripe/silverstripe-assets/blob/3d842a160163366456ba504dba00920d1f10fa20/src/FilenameParsing/FileIDHelperResolutionStrategy.php#L439) for variants and should be calling `$filesystem->listContents($folder, false)` to only get the files that are in the current directory the asset is stored in. Otherwise any asset that is in the root asset directory will on publish need the file system to loop through every asset that exists to compare if it is a variant of the uploaded asset or not

## Recreating the issue in a new install:
- First we create a new project from the recipe:  
  `composer create-project silverstripe/recipe-cms ./asset `
- Then login to that new site and add an asset to the file system at the top level
- Save and publish that file
- In the terminal go into the assets directory:
  `cd asset/public/assets`
- Run `composer create-project silverstripe/recipe-cms ./example` to create a large amount of files in the folder
- Run `cd example/public/public && rm -rf _resources` to remove symlinked resources (Flysystem local adapter doesn't support symlinks)
- Run `cd example/vendor && rm -rf bin` to remove symlinked files from composer
- Replace the uploaded assets file in the admin
- Click publish

Depending on your file systems speed you might not notice a slow down but if you want to check the amount of files you can edit `vendor/league/flysystem/src/Adapter/Local.php` file to change the listContents function to before the return statement execute `echo count($result); exit;` and see the amount of files, in my case it was 10904 files or an array of 1.7mb size.

You can then edit `vendor/silverstripe/assets/src/FilenameParsing/FileIDHelperResolutionStrategy.php` file to change the call to `listContents` to call the recursion with false and you get 10 items or 1092 bytes size

**Comment by emteknetnz** [comment]
@adrhumphreys would you be able to create a PR with your proposed fix so that it runs through travis so we'll get an idea if it will break anything obvious

**Comment by adrhumphreys** [comment]
I've created a quick [PR](https://github.com/silverstripe/silverstripe-assets/pull/415) I feel like this will require some more testing/validation on the effect it has when files are moved around etc

**Comment by emteknetnz** [comment]
Thanks for the PR

![image](https://user-images.githubusercontent.com/4809037/88739092-c4c41480-d18d-11ea-9122-9a5c6cd06004.png)

:-/

Seems like we may need a slightly different approach

If your error you have 1GB of RAM being exceeded, though you're saying that on 10K records you're getting an array of 1.7MB.  Is that 10K records in an array, or is that 10K entire File objects?

**Comment by adrhumphreys** [comment]
The way the issue appeared was when a user tried to publish a page we would get an exception with the message:

```sql
SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:

UPDATE "SiteTree"
SET "HasBrokenFile" = ?, "HasBrokenLink" = ?, "NextReviewDate" = ?, "Content" = ?, "ExtraMeta" = ?, "PublishOnDate" = ?, "UnPublishOnDate" = ?, "LastEdited" = ?

WHERE ("ID" = ?)

HY000-1205: Lock wait timeout exceeded; try restarting transaction
```

This was then tracked down to the asset publish timing out on our server (nginx automatically timesout after 4 mins)

You could then look at the logs recorded during this time and fine the exception:
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/mysite/releases/109e675fcf8706f941db7148f275f685ee0feb5b/vendor/league/flysystem/src/Adapter/Local.php on line 508
```

So you can see we were hitting the server limit of 256mb

We then created a dev task which looked like the following:
```php
$video = Video::get_by_id((int) $id);
$video->publishRecursive();
```

Running this through sake would then give us 1gb of memory since it was via the CLI, this would run for sometimes 20mins other times an hour or so before returning the memory issue. 

So from this my assumption would be that even if we chunked the amount it's still limiting the amount of files you can have on a server to the speed you can recursively iterate through them and get the metadata on request

**Comment by emteknetnz** [comment]
Could you elabroate a bit more what your 1GB dev/task is doing exactly? The sample you've provided is only publishing a single Video DataObject which doesn't seem like it's going to take 20 minutes?

Or is that literally the dev/task the `recursivePublish()` cascade publishes thousands of records?

**Comment by adrhumphreys** [comment]
The dev task is to publish the one file (sorry `Video` is context from the app but just extends `Image` with some extra metadata. _Extra context the application we're working on has >800gbs of assets._).

Therefore when we publish one asset in the root directory (after replacing the file) the assets code goes to delete any variants that file could have had.
That call to delete those variants creates a `RecursiveDirectoryIterator` setting the starting path as `assets` and then loops through all the files and folders in the `assets` directory (all 800gbs of assets)

The reason the dev task takes so long is because of needing to iterate over all those files and directories
The reason the dev task hits the memory limit is because the array grows too large, hence the exception is when it's trying to allocate only 20480 bytes (20kb) to memory as it reads the metadata of one more file

**Comment by chrispenny** [comment]
As I understand it... Simplified steps, as an example:

- User creates an asset in the root of the Asset Admin.
- User requests to delete that asset.
- The Asset Store understands that it needs to delete the old variant files for that asset (eg the CMS preview variants).
- As part of the attempt to find those variants, `$filesystem->listContents($folder, true)` is called.

The `$folder`, in this case, is `/var/www/mysite/www/public/assets` (because this is where the asset is currently stored on the file system).

The second parameter (that is currently set to `true`) is the flag to indicate that we should recursively process folders that are found and collate the contents from all of them.

Given that the `$folder` provided is the asset root, this recursive call is going to mean that we "list contents" for every folder in our asset file system. Which, in our case, is many 100s of thousands of files.

While it's true that `publishRecursive()` can trigger this behaviour, it is not the cause. In the original example, the reason it creates this issue is because we performed a "replace", and the deletion of variants occurs when you publish the asset.

**Comment by emteknetnz** [comment]
The linked PR has been tested and merged.

Thanks for the contribution!
