### ISSUE TITLE
Large file uploads on Heroku in SS 4

### ISSUE THREAD

**Issue by filiplikavcan** [silverstripe/silverstripe-assets#421]
Heroku terminates script execution after 30 seconds. That is why it is not possible to upload large files in SS4.

The solution could be chunked upload. Is there any plan to implement it?

It's an annoyance in the mechanism preventing it from running reliably on certain hosting setups. If anything, it could be called an edge case requiring an enhancement to the current status for a limitation devs may not always be able to control.

**Comment by dhensby** [comment]
There are community modules available: https://packagist.org/packages/bigfork/silverstripe-dropzone

**Comment by filiplikavcan** [comment]
"A Dropzone.js field for SilverStripe 4 - designed to be used on the frontend, not in the CMS."

**Comment by bergice** [comment]
Like @dhensby said you could use the dropzone module, your files would still end up in the assets area. It may not be as streamlined of a solution though.

Maybe it would be possible to use a background job instead?

Heroku recommends using S3 for large file uploads, could that be another solution?
https://devcenter.heroku.com/articles/request-timeout#uploading-large-files

**Comment by micschk** [comment]
@filiplikavcan I had an SS3 [module to activate chunked uploads](https://github.com/micschk/silverstripe-chunkeduploadfield) in the existing uploadfield. Haven't upgraded it to SS4 though (and probably will not either since anything involving the react layer in SS4 has become exponentially more work). 

But maybe it can serve as a starting point to enable chunked uploads in SS4.

**Comment by obj63mc** [comment]
From testing the Dropzone module on the frontend with a chunked upload, you will still have issues on Heroku.  It will get the file to the server properly.  But if you are using the S3 Module to then push via flysystem to S3 - that then needs to upload the file from the heroku server to S3 and that itself will take longer than 30 seconds so when the chunked upload is waiting for the final response it will fail.

On Heroku you will pretty much have to implement a frontend specific solution like their Node example to handle large uploads.   It basically bypasses the backend and is uploaded direct to S3 from the frontend. 

Their solution you basically submit an AJAX request to the backend which creates a Signed AWS request.  That is then CORS AJAX requested from the frontend with the file contents to your S3 bucket and uploads the file.  You would then have to make a final request to your backend with the rest of the form information or the response so you can programmatically add the Asset to the DB so it will be in the assets section.

https://devcenter.heroku.com/articles/s3-upload-node

Definitely not clean.  I have found though that with Heroku you are pretty much good for any files smaller than 25MB so I have really only had issues with things like videos or large PDFs

**Comment by dhensby** [comment]
I think this issue should be closed - we don't make any promises around compatibility with Heroku nor around chunked uploads. This is bordering on a feature request, which we don't track in the github issues.

Having an s3 implementation that retrieves the signed AWS request, etc is out of scope for this module.
