### ISSUE TITLE
Exception in `Folder::find_or_make()` if Versioned not installed

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-assets#422]
As of silverstripe/assets v1.6.1 it is now impossible to `Folder::find_or_make()` if Versioned is not installed, caused by:
```
$versioned = Injector::inst()->get('SilverStripe\Versioned\Versioned');
```
Injector returns an `InjectorNotFoundException()`.

My guess is that this part of the code should potentially have a wrapping `if (class_exists(Versioned::class))...`.

**Comment by michalkleiner** [comment]
Or make it actually work without `Versioned`.
