### ISSUE TITLE
ImageShortcodeProvider doesn't seem to process [img shortcodes with empty title="" or alt=""

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-assets#435]
After running the TagsToShortcode task some images ended up with an empty title or alt attribute, which didn't seem to get processed correctly by the shortcode provider. 

Upon saving, the attributes have four """" instead of two. (Eg `[image ... title="""" alt="""" ]`. Two more get added upon each save...

See also: https://github.com/silverstripe/silverstripe-cms/issues/2489

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9872

**Comment by maxime-rainville** [comment]
Thanks for taking the time to report this bug.

Can you provide the exact HTML strings that are causing problems, before and after running the `TagsToShortcode` task. This will make it easier for us to debug the issue.

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/9872 should fix this
