### ISSUE TITLE
Expected behavior for files and folders with permission restrictions applied

### ISSUE THREAD

**Issue by LeviWB** [silverstripe/silverstripe-assets#449]
I am a bit confused after reading through https://github.com/silverstripe/silverstripe-framework/issues/8493 and https://docs.silverstripe.org/en/4/developer_guides/files/file_security/, as well as my own testing to figure out what is meant to happen when permissions are applied to assets via the CMS and a user attempts to access the file itself.

Here are a couple of scenarios where I'm not sure whether what is happening is what is expected:

### Published file with view permission access restriction applied (e.g. 'Only these groups' or 'Logged-in users')
An anonymous user **cannot** access the file itself. This seems like correct to me, although does seem to contradict the information in the [developer guide](https://docs.silverstripe.org/en/4/developer_guides/files/file_security/) _Published and unprotected files can be downloaded by anyone knowing the URL. They bypass any SilverStripe permission checks (served directly by the webserver)_

### Published file with view permission 'Inherit from parent folder', inside a folder with view permission access restriction applied (e.g. 'Only these groups' or 'Logged-in users')
An anonymous user **can** access the file itself. Given what I observed in the first scenario, I would've also thought that files inside a folder that have an access restriction applied would not be accessible.

**Comment by michalkleiner** [comment]
The first one is correct and the guide may need updating.
The second one is an issue, are you sure it behaves like that? It should respect the parent folder permissions if set to inherit. What version of the module are you using?

**Comment by LeviWB** [comment]
@michalkleiner Thanks for clarifying the expected behavior. Apologies I was using 1.7.0 but have just tried 1.8.0, and the files are inheriting the permissions as expected from the folders in 1.8.0. I will close this issue.
