### ISSUE TITLE
WYSIWYG image renders `loading` attribute

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-assets#451]
**Blocked by https://github.com/silverstripe/silverstripe-asset-admin/issues/1214**

### Overview

Modify `ImageShortcodeProvider.php` to render the new lazy-loading attribute.

Background: https://forum.silverstripe.org/t/browser-level-lazy-loading-from-silverstripe-cms/4218

web.dev article - https://web.dev/browser-level-lazy-loading-for-cmss/

### Acceptance Criteria

- [x] The image shortcode provider is updated so that the loading=lazy attribute is added to the tag by default
- [x]  The loading="lazy" attribute will only be added to images where dimensions are defined
- [ ] ~~Where an image opts out of lazy-loading, the loading attribute should be skipped entirely~~
- [x] Where a site has globally opted out of lazy-loading, the loading attribute is skipped
- [x] Ensure that when the image is loading **in the CMS**  the image does not have the `loading` attribute
- [ ]  ~~A 'dummy' checkbox is created to enable/ disable lazy-loading on a per image basis in the placement tab, to show this working~~
  - ~~we'll follow up on this in a dedicated UX card~~
- [ ] ~~The checkbox does not show if a site has globally opted out of lazy-loading~~

### Notes
- It was discussed that it would be interesting to test having the WYSIWYG **in the CMS** lazy-load the images by default too. 

### PRs
- [x] https://github.com/silverstripe/silverstripe-assets/pull/455

**Comment by bergice** [comment]
You may need to whitelist the `loading` attribute on `img` elements using `extended_valid_elements`, otherwise it will be stripped from the source when the content is saved.
