### ISSUE TITLE
Set your own `loading` value globally

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-assets#453]
### Overview

In addition to the [opt-out functionality](https://github.com/silverstripe/silverstripe-assets/issues/452) we've discussed adding the option to allow developers to set their own global value for the `loading` attribute, i.e changing this from `loading="lazy"` to `loading="eager"`, `loading="auto"`, or any future option. 

Background: https://forum.silverstripe.org/t/browser-level-lazy-loading-from-silverstripe-cms/4218

### Acceptance Criteria

- [ ] There is the option for a Developer to set the default value, opting to retain the loading attribute and changing it to something else
- [ ] The downstream affects of changing this to a value won't be supported by the CMS field used by content editors is clear
- [ ] Images that don't have a predefined value default to using this value in the SSViewer
- [ ] Images that don't have a predefined value default to using this value in the image shortcode

### Notes
- A migration task would be out of scope should this be changed halfway through a project and images across the project be in two different states.

**Comment by brynwhyman** [comment]
I think this idea is a no-go. [Google make recommendations against this](https://web.dev/browser-level-lazy-loading-for-cmss/#allow-per-element-modifications):

> Caution: If an element should not be lazy-loaded, require or encourage skipping the `loading` attribute entirely. While using `loading="eager"` is a supported alternative, this would tell the browser explicitly to always load the image right away, which would prevent potential benefits if browsers implemented further mechanisms and heuristics to automatically decide which elements to lazy-load.

**Comment by emteknetnz** [comment]
Happy to close issue, not supporting this reduces complexity

@clarkepaul would mean you only need to design UX around the scenario where lazy loading is the global default

**Comment by brynwhyman** [comment]
Based on the above quote from Google, I can't see a reason why we should go ahead with this. Closing.

**Comment by bergice** [comment]
> I think this idea is a no-go. [Google make recommendations against this](https://web.dev/browser-level-lazy-loading-for-cmss/#allow-per-element-modifications):
> 
> > Caution: If an element should not be lazy-loaded, require or encourage skipping the `loading` attribute entirely. While using `loading="eager"` is a supported alternative, this would tell the browser explicitly to always load the image right away, which would prevent potential benefits if browsers implemented further mechanisms and heuristics to automatically decide which elements to lazy-load.

I don't see how this has anything to do with changing the default.

If they set it to `eager` we can just ignore rendering.

This has nothing to do with rendering vs not rendering things.

**Comment by emteknetnz** [comment]
Changing the default value is kind of redundant.  If you want to eager load by default then just use the global opt out config.  There's only 2 functional values so a boolean config is fine.

By making the default value configurable it increases the complexity and worked around messaging on the UX component since you need to support multiple scenarios, rather than just one, though for basically no benefit.
