### ISSUE TITLE
Allow users to upload WebP images

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#486]
WebP images support is ubiquitous now. There's not much point left to block people from uploading them to the CMS.

# Acceptance criteria
- [x] WebP images can be uploaded to the CMS assets section
- [x] WebP files are handle has images and can be added ho WYSIWYG
- [ ] Clear steps are provided for developers who wish to disable this feature.

# Pull request
- [x] https://github.com/silverstripe/silverstripe-assets/pull/476
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10282
- [x] https://github.com/silverstripe/silverstripe-userhelp-content/pull/172

**Comment by dhensby** [comment]
Can this be closed now #476 is merged?

**Comment by maxime-rainville** [comment]
Still need to update the changelog/doc to explain how to disable the feature for folks who don't want it.

**Comment by GuySartorelli** [comment]
All connected PRs are merged.
