### ISSUE TITLE
CMS5 Upgrade to league/flysystem v3

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#497]
## Acceptance criteria
- [x] CMS5 is updated to use `league/flysystem v3`
- [ ] Where possible use the flysystem interface instead of actual classes

## PR
- https://github.com/silverstripe/silverstripe-assets/pull/524

## silverstripe/installer CI run
- https://github.com/emteknetnz/silverstripe-installer/actions/runs/3358146854

**Comment by sabina-talipova** [comment]
@maxime-rainville , 
The module already requires `"symfony/filesystem": "^6.1"`.

**Comment by emteknetnz** [comment]
Linked PR has been merged
