### ISSUE TITLE
Draft Image not shown when previewing the page

### ISSUE THREAD

**Issue by mark-a-j-adriano** [silverstripe/silverstripe-assets#499]
### Summary: As a user with 'Previewers'  [VIEW_DRAFT_CONTENT] access, I want to view all content on a draft web page.
Currently, they cannot see any images that are not published.

**Scenario 1:**
- Login as Admin 
- Create a Draft page
- Insert a Draft Image to the WYSIWYG editor (Rich text field)
- Preview the page (Copy preview link)
- Log out Admin
- Preview the page (Use the preview link)
- Login as Admin  
- Preview the page (Use the preview link)

**Expected:**  Preview of the page will show the draft content + image
**Actual:**  Preview of the page will show the draft content without the draft image
_Note_ : When I go in as Admin and edit the page (wait for it to load the image in the CMS) then try to preview the page again then the image shows up. (like a pre-warm procedure maybe?)

**Scenario 2:**
- Login as Admin 
- Create a Draft page
- Insert a Draft Image to the WYSIWYG editor (Rich text field)
- Preview the page (Copy preview link)
- Log out Admin
- Preview the page (Use the preview link)
- Login as a User with `VIEW_DRAFT_CONTENT` role  
- Preview the page (Use the preview link)
**Expected:**  Preview of the page will show the draft content + image
**Actual:**  Preview of the page will show the draft content without the draft image

**Scenario 3:**
- Login as Admin 
- Create a Draft page
- Insert a Draft Image to the WYSIWYG editor (Rich text field)
- Copy the link (Share button via the `Share Draft Module`)
- Log out Admin
- Preview the page (Use the Share link) 
**Expected:**  Preview of the page will show the draft content + image
**Actual:**  Preview of the page will show the draft content without the draft image

Modules installed:
 "name": "silverstripe/cms",
 "version": "4.8.0",
 "name": "silverstripe/framework",
  "version": "4.8.0",
 "name": "silverstripe/sharedraftcontent",
 "version": "2.5.1",
 "name": "silverstripe/assets",
  "version": "1.8.0",

<img width="839" alt="Screen Shot 2022-07-04 at 11 25 56 AM" src="https://user-images.githubusercontent.com/11882563/177060745-b66148e3-c46a-475a-9fff-6d056359cf59.png">

**Comment by GuySartorelli** [comment]
In all of these scenarios, the user who created the page is an admin. Is this also a problem if someone with less-than-admin privileges creates the page?

**Comment by mark-a-j-adriano** [comment]
@GuySartorelli  -> Yep, I used a `Content Author` and the same issue as above. Roles included : 
![Screen Shot 2022-07-07 at 12 32 03 PM](https://user-images.githubusercontent.com/11882563/177667696-39d37044-e79b-40a2-bca5-eb5c6b44d142.png)

**Comment by emteknetnz** [comment]
Note our cucumber test for share draft content did not include an image for the test - I've updated this now

This seems a little weird to be honest - we have made a couple of bugfixes in the last year or so that have touched the file grant logic, I wonder if one of those would have resolved this.

@mark-a-j-adriano I noticed you're running 4.8 - could I get you to double check this on a more recent version of silverstripe?

`composer create-project silverstripe/installer:^4.11` and `composer require silverstripe/sharedraftcontent:^2.7` and then see if you're able to replicate the issue above

**Comment by mark-a-j-adriano** [comment]
@emteknetnz  -> looks like working for all scenarios for the latest cms and share draft content modules. Looks like this is more pushing clients to update to the latest modules then.

**Comment by emteknetnz** [comment]
Great to hear, thanks for taking the time to report and replicate this issue. I'll close this one.
