### ISSUE TITLE
Still using a slightly legacy asset resolution strategy by default

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-assets#541]
Installer overrides the default assets file resolution strategy - this is a holdover from when this stuff was introduced in CMS 4.4

The assets module should use the optimal strategy by default, and installer should stop overriding it at all.

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/542
- https://github.com/silverstripe/silverstripe-installer/pull/350

**Comment by maxime-rainville** [comment]
All merged.
