### ISSUE TITLE
Error when previewing page and asset doesn't exist

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-assets#545]
"[Emergency] Uncaught TypeError: Return value of SilverStripe\Assets\Shortcodes\FileShortcodeProvider::getCachedMarkup() must be of the type string, null returned"

Granted, this is a feature of `silverstripe/cms`, however the culprit is logic found in `silverstripe/assets`, specifically in `FileShortcodeProvider::getCachedMarkup()`

`return $item['markup'];` <-- can return null. A simple null coalesce operator "fixes" it ala `return $item['markup'] ?? ''`, but there may be issues in `silverstripe/cms` or `silverstripe/framework` where this array value should never be `null`. I think this has just surfaced when an explicit `:string` return type was naively added to the method.

Using Silverstripe `4.12.3` on PHP 7.4

PR
- https://github.com/silverstripe/silverstripe-assets/pull/562

**Comment by GuySartorelli** [comment]
Thanks for reporting this.
Can you please give a clear set of steps to reproduce this error? You mention previewing a page when an asset doesn't exist - but you haven't described for example how the asset relates to the page?

**Comment by GuySartorelli** [comment]
PR merged and tagged as [1.13.3](https://github.com/silverstripe/silverstripe-assets/releases/tag/1.13.3) and [2.0.4](https://github.com/silverstripe/silverstripe-assets/releases/tag/2.0.4)
