### ISSUE TITLE
FileLinkTracking::augmentSyncLinkTracking should not make make queries if there are no tracked fields

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-assets#557]
Recently found this by chance

It seems that since FileLinkTracking is attached to the dataobject, it runs for classes that are not relevant (eg: LoginSession)

<img width="1909" alt="image" src="https://github.com/silverstripe/silverstripe-assets/assets/250762/58db0080-5f30-4aa0-9e51-967c9bc32a6f">

By checking if there are actually any DBHTMLText, the query is not happening anymore

```php
        // Build a list of HTMLText fields, merging all linked pages together.
        $allFields = DataObject::getSchema()->fieldSpecs($this->owner);
        $linkedPages = [];
        $anyBroken = false;
        $hasTrackedFields = false;
        foreach ($allFields as $field => $fieldSpec) {
            $fieldObj = $this->owner->dbObject($field);
            if ($fieldObj instanceof DBHTMLText) {
                $hasTrackedFields = true;
                // Merge links in this field with global list.
                $linksInField = $this->trackLinksInField($field, $anyBroken);
                $linkedPages = array_merge($linkedPages, $linksInField);
            }
        }

        if (!$hasTrackedFields) {
            return;
        }
```

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/558
- https://github.com/silverstripe/silverstripe-cms/pull/2863

**Comment by lekoala** [comment]
same thing for SiteTreeLinkTracking

maybe i'm missing something, but these changes seem to save two queries :-)

**Comment by GuySartorelli** [comment]
Both PRs are merged. Thanks for that.
