### ISSUE TITLE
AssetControlExtension should run less queries

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-assets#559]
Since it's an extension applied to all dataobject, extra caution should be taken in onBeforeWrite

https://github.com/silverstripe/silverstripe-assets/blob/e57099b0f1bfa63509307fe8da290c1dfe7a4ed1/src/AssetControlExtension.php#L72-L83

This kind of code can lead to this

<img width="1551" alt="image" src="https://github.com/silverstripe/silverstripe-assets/assets/250762/4ef49f56-717d-472d-87e2-256c09b6f371">

If i understand this correctly, it means we run an uncached select query, on each write, for any dataobject ?
that can't be right ? right ?

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/560

**Comment by lekoala** [comment]
example solution provided as PR

**Comment by GuySartorelli** [comment]
PR merged - it will be automatically tagged when CI has finished running on the branch.
