### ISSUE TITLE
Add support for braille format files

### ISSUE THREAD

**Issue by edwilde** [silverstripe/silverstripe-assets#573]
Add support for the [Braille ASCII file format](https://en.wikipedia.org/wiki/Braille_ASCII) to be allowed to be uploaded by CMS editors by default.

This is commonly asked for in the public sector and implemented using custom configuration.

Braille ASCII files are just plain text, so should not pose any security risk. However, I am not pen tester ;)

## Notes
It seems, there is disagreement on what mime type `brf` files should be: datatypes.net says it should be `application/octet-stream` ([ref](https://datatypes.net/open-brf-files)), but apache says it should be `text/plain` ([ref](https://bz.apache.org/bugzilla/show_bug.cgi?id=41240)). In custom configurations we typically add both but `text/plain` seems to be more common.

## Related issue
- https://github.com/silverstripe/silverstripe-assets/issues/572

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10970
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/68
- https://github.com/silverstripe/silverstripe-assets/pull/574

**Comment by GuySartorelli** [comment]
PRs merged. This will be included in the Silverstripe CMS 5.2.0 release.

**Comment by edwilde** [comment]
Thanks for your help with this @GuySartorelli, much appreciated 🎉
