### ISSUE TITLE
Shortcode are not being cached

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#597]
### Module version(s) affected

2.2.0, but probably all version of 2

### Description

The method that's meant to check the cache for `FileShortcodeProvider` and `ImageShortcodeProvider` will always return an empty string unless you allow session grant.

In CMS4, I think session grant was enabled by default so this wasn't a problem.

https://github.com/silverstripe/silverstripe-assets/blob/ff5e8a743eea9cdddb900579a6e8c3d77a48e8ba/src/Shortcodes/FileShortcodeProvider.php#L137-L150

### How to reproduce

- Add a `die('cache hit');` statement in this `if` clause https://github.com/silverstripe/silverstripe-assets/blob/ff5e8a743eea9cdddb900579a6e8c3d77a48e8ba/src/Shortcodes/ImageShortcodeProvider.php#L59-L64.
- Add an Image to a WYSIWYG and publish the page.
- Access the page twice.

Expected results: I hit the die statement.
Actual: My cache check always returns a blank string and I regenerate the short code each time.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## Pull request
- https://github.com/silverstripe/silverstripe-assets/pull/598

**Comment by GuySartorelli** [comment]
@maxime-rainville Please link to any revelant PRs since this is in the peer review column

**Comment by maxime-rainville** [comment]
Added a link to PR https://github.com/silverstripe/silverstripe-assets/pull/598

**Comment by GuySartorelli** [comment]
PR merged. Will be automatically tagged by GitHub actions
