### ISSUE TITLE
Possible to hit “a non-numeric value was encountered” errors in PHP 7.1+

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-assets#6]
See https://travis-ci.org/silverstripe/silverstripe-framework/jobs/218382148#L550.

This is still an issue, even though the test isn’t currently triggering it. The [test that does trigger this in 3.x](https://github.com/silverstripe/silverstripe-assets/blob/8f48409b0c81acbcd28c7608514fff50e9fa4280/tests/php/ImageTest.php#L235-L243) doesn’t trigger it anymore because `Image::CropHeight()` now results in a call to `Image_Backend::croppedResize()` instead of `Image_Backend::resizeByHeight()` - and `croppedResize()` calls `round()` on the string argument, casting it to an int.

https://github.com/silverstripe/silverstripe-framework/pull/6771/commits/788ca7f7b8516f3ca18ef2d56d5637578960a6a0 is the fix I’ve currently submitted, pending review.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6771
