### ISSUE TITLE
.webp file gives `403` error when viewing even if I'm admin

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-assets#659]
In CMS 6 (haven't tested 5.3, check that before implementing a fix) I can upload .webp files just fine, but attempting to view them (even the thumbnails in asset-admin after a refresh) gives a 403 error.

**Comment by emteknetnz** [comment]
Cannot replicate on either CMS 5 or CMS 6. I tried using the "tree" webp sample on https://developers.google.com/speed/webp/gallery1 (I've double checked I tested using the webp, not the jpeg)

**Comment by GuySartorelli** [comment]
I assume you mean `4.webp` - that file also gives me this behaviour. Might be a dev environment specific problem, I'll have to investigate further. For reference I'm using DDEV.

**Comment by GuySartorelli** [comment]
Looks like my `public/assets/.htaccess` file isn't including webp in the allowed file extensions. Adding it manually resolves this.
@emteknetnz Can you please check for `webp` in the `RewriteCond` line of that file after the "# Block invalid file extensions" comment?

**Comment by GuySartorelli** [comment]
Further on this - deleting that htaccess file and then making a request to my site results in the file being regenerated, which _does_ include webp.

So I think what's happening is Silverstripe CMS is finding the copy of https://github.com/silverstripe/silverstripe-installer/blob/5/public/assets/.htaccess in my public/assets dir and going "cool the file exists, no need to recreate it"

**Comment by emteknetnz** [comment]
My `public/assets/.htaccess` file contains webp

```
    # Allow specific file extensions
    RewriteCond %{REQUEST_URI} !^[^.]*[^\/]*\.(?i:css|js|ace|arc|arj|asf|au|avi|bmp|brf|bz2|cab|cda|csv|dmg|doc|docx|dotx|flv|gif|gz|hqx|ico|jpeg|jpg|kml|m4a|m4v|mid|midi|mkv|mov|mp3|mp4|mpa|mpeg|mpg|ogg|ogv|pages|pcx|pdf|png|pps|ppt|pptx|potx|ra|ram|rm|rtf|sit|sitx|tar|tgz|tif|tiff|txt|wav|webm|webp|wma|wmv|xls|xlsx|xltx|zip|zipx|graphql)$
    RewriteRule .* - [F]
```

**Comment by GuySartorelli** [comment]
Whatever was causing this has stopped causing it
