### ISSUE TITLE
ImageManipulation of transparent PNGs result in black background

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-assets#66]
When using any of the `ImageManipulation` methods (eg: `ScaleWidth` & `Fill` etc) on a transparent PNG image, the background ends up black.

I would think that the expected result would to to maintain transparency.

**Comment by dhensby** [comment]
Verified this is happening - it's going to be an issue with the upstream library, though `intervention/image`

**Comment by axllent** [comment]
You're right @dhensby and I see you commented on an open issue via intervention/image#457 (thanks for that).

Now what really sucks is that this issue was opened (intervention/image) almost two years ago and still isn't fixed - and now SilverStripe inherits that problem which will affect any transparent PNG image rendering (scaling / cropping) in SS4. Maybe SilverStripe can put some pressure on intervention/image to fix it, or possibly provide an upstream fix for them?

**Comment by dhensby** [comment]
fix at https://github.com/Intervention/image/pull/776

**Comment by axllent** [comment]
I can confirm this upstream fix has solved the issue, thanks Daniel!

**Comment by dhensby** [comment]
@axllent it's not been tagged too :) - 2.4.1
