### ISSUE TITLE
MigrateFileTask doesn't remove original files

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-assets#70]
The task migrates files into the new folder structure (hash-based), but leaves the originals in place. This will at least double the required disk space, and cause clutter that's hard to fix up manually (old folders co-exist on the same level as new ones). The [upgrading docs](https://docs.silverstripe.org/en/4/changelogs/4.0.0/#migrating-file-dataobject-from-3-x-to-4-0) don't mention this either.

@tractorcow What's the reason for not deleting those?

Note: There's a [resampling issue](https://github.com/silverstripe/silverstripe-assets/issues/69) which will further increase disk space use.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/92

**Comment by tractorcow** [comment]
Unintentional; These files should be deleted. This wouldn't be too difficult.
