### ISSUE TITLE
Image manipulation (ScaleWidth) unexpected orientation result

### ISSUE THREAD

**Issue by colymba** [silverstripe/silverstripe-assets#76]
Thought it was a front end issue of some sort originally, but `ScaleWidth` has unexpected result in terms of image orientation, changing the output from portait to landscape randomly.

See example output below (original is portrait):

![screen-shot-2017-10-02-at-11 10 10- 2](https://user-images.githubusercontent.com/978040/31068979-101d7442-a763-11e7-904b-5ce8d86b2446.jpg)
-
![screen-shot-2017-10-02-at-11 14 04- 2](https://user-images.githubusercontent.com/978040/31068978-101ba374-a763-11e7-80e1-3922ab8b6809.jpg)
-

The original image has Exif data, which I guess might be the problem looking at other (maybe related) instance: https://github.com/silverstripe/silverstripe-assets/issues/36 and https://github.com/silverstripe/silverstripe-assets/pull/34

**Comment by dhensby** [comment]
Thanks for reporting this - I'll look into it, would you mind supplying the original image? Alternatively can you confirm you can reproduce this with one of the [exif test images](https://github.com/recurser/exif-orientation-examples) and let me know which?

**Comment by colymba** [comment]
didn't test all of them, but from the exif test images (landscape 1-4), number 1 was fine, then 2 to 4 all had issues:

![screen shot 2017-10-02 at 13 09 02](https://user-images.githubusercontent.com/978040/31073391-63378fc6-a774-11e7-8786-17b701fec146.png)
-
![screen shot 2017-10-02 at 13 09 05](https://user-images.githubusercontent.com/978040/31073386-6321f260-a774-11e7-9315-f9f2dc14a2b1.png)
-
![screen shot 2017-10-02 at 13 12 30](https://user-images.githubusercontent.com/978040/31073387-6323086c-a774-11e7-954f-1b0291fcd42e.png)
-
![screen shot 2017-10-02 at 13 12 34](https://user-images.githubusercontent.com/978040/31073390-6325f7de-a774-11e7-95f9-c618d3688be0.png)
-
![screen shot 2017-10-02 at 13 13 33](https://user-images.githubusercontent.com/978040/31073388-6324280a-a774-11e7-9d8e-cff8eb47c94a.png)
-
![screen shot 2017-10-02 at 13 13 35](https://user-images.githubusercontent.com/978040/31073389-6325b2c4-a774-11e7-9cae-6150a1355272.png)
 
template code with method and sizes called:
````
<picture>
<source srcset="$Image.ScaleMaxWidth(1400).URL" media="(min-width: 100em)">
<source srcset="$Image.ScaleMaxWidth(916).URL" media="(min-width: 60em)">
<source srcset="$Image.ScaleMaxWidth(896).URL" media="(min-width: 30em)">
<!--[if IE 9]></video><![endif]-->
<img src="$Image.ScaleMaxWidth(464).URL" />
</picture>
````

weird thing is that `ScaleMaxWidth(1400)` seems always right, just issues with lower resolution...

**Comment by dhensby** [comment]
Brilliant, thanks so much for that - I'll look into it

**Comment by colymba** [comment]
Reading up on the whole exif issue... seems to me using `->orientate()` before manipulating the images would solve this, but it is dependant on exif data being available... 

So, waiting on PHP 7.2 (which might not be long) or your PR at https://github.com/Intervention/image/issues/745

**Comment by dhensby** [comment]
OK - thanks a lot for finding this because it's also uncovered a bug where image manipulations would actually happen before orientation which means you'd be changing the height of files when you wanted the width and vice versa because orientation happens after manipulation and not before.
