### ISSUE TITLE
CLI Flush & Asset Permissions

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-assets#81]
When running the following from the command line (in SS4)..

> php vendor/silverstripe/framework/cli-script.php dev/build flush=1 disable_perms=1

The `/assets/.htaccess` and `/assets/.protected/.htaccess` files don't get created. However, running the same thing from the browser causes them to be created (only a flush is actually needed). At first I thought it may have been a permission thing (similar to https://github.com/silverstripe/silverstripe-framework/issues/3092), however I've narrowed it down to the following..

- https://github.com/silverstripe/silverstripe-assets/blob/3eefceca9bfee98cb16843ceb673e4c412235aa0/src/Flysystem/AssetAdapter.php#L124

When hitting this from the browser, the type comes through as **apache** (in my case). However doing this from the command line, the type comes through as **php**. So neither of the following are hit..

- https://github.com/silverstripe/silverstripe-assets/blob/1/src/Flysystem/PublicAssetAdapter.php#L24
- https://github.com/silverstripe/silverstripe-assets/blob/1/src/Flysystem/ProtectedAssetAdapter.php#L22

This is currently my work around, but it seems like we should be able to pass something through to the cli-script such as `type=apache` at the very least.

- https://github.com/symbiote/silverstripe-build/blob/master/configs/silverstripe/local.sample.yml

Thoughts?

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7488
- [x] https://github.com/silverstripe/silverstripe-assets/pull/91

**Comment by chillu** [comment]
Hmm, yeah it's just a bit too much magic, isn't it? We can't mandate that you run `dev/build` through a browser/webserver. And this is an essential setting, so we have to be careful with adding explicit steps that might be missed and accidentally expose protected files, as well as break website operation (not redirecting correctly). @tractorcow Ideas?

**Comment by tractorcow** [comment]
I suggest an env var for cli, and assume Apache if not configured.

**Comment by flamerohr** [comment]
one issue when implementing this is the file permissions on the generated `.htaccess` files:
if it's generated by the web-user (_www, www-data, etc) then the using CLI will not have access to those files unless you log in specifically to the web-user to run the CLI.

@tractorcow has suggested something similar to this to address a part of the issue:
```
--- a/src/Flysystem/AssetAdapter.php
+++ b/src/Flysystem/AssetAdapter.php
@@ -133,7 +133,7 @@ class AssetAdapter extends Local
 
         // Apply each configuration
         $config = new FlysystemConfig();
-        $config->set('visibility', 'private');
+        $config->set('visibility', 'public');
         foreach ($configurations as $file => $template) {
             // Ensure file contents
             if ($forceOverwrite || !$this->has($file)) {
@@ -145,7 +145,7 @@ class AssetAdapter extends Local
                 }
             }
             // Ensure correct permissions
-            $this->setVisibility($file, 'private');
+            $this->setVisibility($file, 'public');
         }
     }
```

**Comment by flamerohr** [comment]
I've added https://github.com/silverstripe/silverstripe-assets/pull/91 and https://github.com/silverstripe/silverstripe-framework/pull/7488 to address this issue :) primarily the `$default_server` config option is now available on the `AssetAdaptor` class.

Other things tweaked were the forgotten but needed file_permissions leniency, and a check before setting file visibility (tiny performance boost).
