### ISSUE TITLE
Readonly image fields still popup when clicked on label

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-assets#95]
**SS: 4.0.0-rc1**

Scenario:

```php
# Page.php
use SilverStripe\CMS\Model\SiteTree;

class Page extends SiteTree
{
    private static $has_one = array(
        'MyImage' => \SilverStripe\Assets\Image::class
    );

    public function getCMSFields()
    {
        $this->beforeUpdateCMSFields(function ($fields) {
            $fields->addFieldToTab('Root.Main', \SilverStripe\AssetAdmin\Forms\UploadField::create('MyImage'));
        });
        return parent::getCMSFields();
    }
}
```

Steps to reproduce:

* Create a page, add some content
* Upload an image
* Save image
* Go to page history, choose a history record
* Click on "My Image" field label

Expected behaviour: nothing happens
Actual behaviour: upload popup is displayed

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/681/files

**Comment by flamerohr** [comment]
Updated pull request https://github.com/silverstripe/silverstripe-asset-admin/pull/681/files with the fix :)
